Last login: Sun Feb  9 13:27:01 on ttys002
StoleYourWiFi:~ onixon$ ssh ozz@siliconu.com
StoleYourWiFi:~ onixon$ ls ~/Downloads/userlist.ans 
/Users/onixon/Downloads/userlist.ans
StoleYourWiFi:~ onixon$ scp ~/Downloads/userlist.ans root@modernpascal.com:/var/LEGACYX/
root@modernpascal.com's password: 
Permission denied, please try again.
root@modernpascal.com's password: 
userlist.ans                                  100% 2617     2.6KB/s   00:00    
StoleYourWiFi:~ onixon$ cd ~/Desktop/
StoleYourWiFi:Desktop onixon$ ls
7zip.zip
Barchart.png
CP437_8x8.png
Colorpane.png
Colorpicker.png
Combobox.png
Datepicker.png
Icon.png
Imagecheckbox.png
Imagetabset.png
Listbox.png
Listgrid.png
Menubar.png
Outlookbar.png
Popupmenu.png
RVACafeGreenShirt.jpg
Scanned from a Xerox Multifunction Printer.pdf
Screen Shot 2019-09-01 at 12.39.05 AM.png
Screen Shot 2019-09-20 at 6.25.05 PM.png
Screen Shot 2019-09-28 at 8.12.07 PM.png
Screen Shot 2019-09-28 at 8.15.13 PM.png
Screen Shot 2019-10-01 at 1.57.12 PM.png
Screen Shot 2019-10-01 at 1.57.30 PM.png
Screen Shot 2019-10-01 at 1.57.51 PM.png
Screen Shot 2019-10-01 at 2.00.13 PM.png
Screen Shot 2019-10-01 at 2.00.33 PM.png
Screen Shot 2019-10-09 at 10.42.56 PM.png
Screen Shot 2019-10-09 at 10.43.33 PM.png
Screen Shot 2019-10-09 at 11.19.14 PM.png
Screen Shot 2019-10-10 at 12.16.14 AM.png
Screen Shot 2020-01-28 at 8.59.33 AM.png
Screen Shot 2020-01-28 at 9.09.53 AM.png
Screen Shot 2020-01-31 at 8.22.55 AM.png
Screen Shot 2020-01-31 at 9.32.56 AM.png
Screen Shot 2020-01-31 at 9.34.53 AM.png
Screen Shot 2020-02-01 at 9.17.42 PM.png
Screen Shot 2020-02-01 at 9.19.13 PM.png
Screen Shot 2020-02-01 at 9.20.11 PM.png
Screen Shot 2020-02-02 at 10.52.42 AM.png
Screen Shot 2020-02-02 at 8.58.44 AM.png
Screen Shot 2020-02-03 at 3.18.08 PM.png
Screen Shot 2020-02-03 at 3.42.57 PM.png
Screen Shot 2020-02-03 at 3.43.39 PM.png
Screen Shot 2020-02-03 at 6.00.28 PM.png
Screen Shot 2020-02-06 at 11.09.27 PM.png
Screen Shot 2020-02-07 at 10.41.18 AM.png
Screen Shot 2020-02-07 at 10.41.56 AM.png
Screen Shot 2020-02-07 at 10.42.29 AM.png
Screen Shot 2020-02-07 at 10.43.03 AM.png
Screen Shot 2020-02-07 at 10.43.52 AM.png
Screen Shot 2020-02-07 at 10.44.09 AM.png
Screen Shot 2020-02-07 at 10.45.42 AM.png
Screen Shot 2020-02-07 at 10.49.06 AM.png
Screen Shot 2020-02-07 at 10.49.29 AM.png
Screen Shot 2020-02-07 at 12.21.39 PM.png
Screen Shot 2020-02-07 at 12.22.08 PM.png
Screen Shot 2020-02-07 at 12.22.21 PM.png
Screen Shot 2020-02-08 at 8.08.48 AM.png
Screen Shot 2020-02-08 at 8.13.26 AM.png
Screen Shot 2020-02-08 at 8.16.06 AM.png
Screen Shot 2020-02-08 at 8.19.39 AM.png
Screen Shot 2020-02-08 at 8.19.55 AM.png
Screen Shot 2020-02-08 at 8.22.34 AM.png
Screen Shot 2020-02-08 at 8.28.08 AM.png
Screen Shot 2020-02-08 at 9.01.18 AM.png
Screen Shot 2020-02-08 at 9.02.47 AM.png
Screen Shot 2020-02-08 at 9.55.43 AM.png
Screen Shot 2020-02-10 at 10.01.37 PM.png
Screen Shot 2020-02-11 at 5.28.27 PM.png
Screen Shot 2020-02-11 at 5.31.12 PM.png
Screen Shot 2020-02-11 at 5.31.59 PM.png
Screen Shot 2020-02-11 at 5.37.16 PM.png
Screen Shot 2020-02-11 at 5.43.36 PM.png
Screen Shot 2020-02-11 at 5.45.13 PM.png
Screen Shot 2020-02-11 at 6.13.50 PM.png
ScreenShots
Scrollbutton.png
Sidebar.png
SmallFonts.ans
Speedbutton.png
Spinedit.png
Splitpane.png
Statusbar.png
Tiny-HTML5-jQuery-Color-Picker-Plugin-Palette-Color-Picker.jpg
Toolbar.png
Tree.png
WellnessRedShirt.jpg
Window.png
WorldCupTKD.jpg
acrobat.zip
angl09v.zip
ansidr11.zip
bbskt30a.zip
bx20bsrc.zip
cirron.zip
colorpicker.jpg
compare.zip
cthug_40.zip
curl7105.zip
cyanide.zip
d12sc.zip
dbase.zip
dci3.zip
dos622.zip
emulxbbs.zip
faq-s.zip
forum250.zip
genopas.zip
gradbook.zip
gsbbs.zip
gwbman.zip
hlc-tm95.zip
imp71src.zip
infinity.zip
infusrc.zip
lc111696.zip
lsd-123s.zip
lsd-123z.zip
magpi01.zip
magpi02.zip
magpi03.zip
magpi04.zip
magpi05.zip
magpi06.zip
magpi07.zip
msrc20b3.zip
mxgui203.zip
neo300s.zip
new.gif
nxdev702.zip
onyxbbs.zip
pipe05bs.zip
psdkv35.zip
quan.zip
safaristand1.png
sauron_s.zip
sbbs45.zip
sh_src94.zip
subbs.zip
tcs150.zip
termbox.zip
tm411reg.zip
tm420-2.zip
tm420-3.zip
tm420-4.zip
tm_iemsi.zip
tmcrack.zip
tpboard.zip
txtq122.zip
vision83.zip
StoleYourWiFi:Desktop onixon$ cd ~/Downloads/
StoleYourWiFi:Downloads onixon$ cd CTM9211
StoleYourWiFi:CTM9211 onixon$ ls
ART1		ART15		ART4		ART7G		FILE_ID.DIZ
ART10		ART16		ART4G		ART8		READER.COM
ART11		ART17		ART5		ART8G		README.1ST
ART12		ART1G		ART5G		ART9		READROOM.TOC
ART13		ART2		ART6		ART9G
ART13G		ART3		ART6G		CTM
ART14		ART3G		ART7		CTMG
StoleYourWiFi:CTM9211 onixon$ cat CTM
  ╔════════════════════════════════════════════════════════════════════════╗
  ║                                                                        ║
  ║                 ▄▄▄▄ ▄▄▄▄ ▄▄▄▄▄ ▄▄▄▄ ▄  ▄ ▄▄▄▄▄ ▄▄▄▄ ▄▄▄▄              ║
  ║                 █    █  █ █ █ █ █▄▄█ █  █   █   █▄   █▄▄█              ║
  ║                 █▄▄▄ █▄▄█ █ █ █ █    █▄▄█   █   █▄▄▄ █ █▄              ║
  ║                           ▄▄▄▄▄ ▄▄▄▄ ▄    ▄ ▄▄                         ║
  ║                             █   █▄▄█ █    █▄█▄                         ║
  ║                             █   █  █ █▄▄▄ █  █ (tm)                    ║
  ║                  ▄▄▄▄▄ ▄▄▄▄ ▄▄▄▄ ▄▄▄▄ ▄▄▄▄ ▄▄▄ ▄▄▄ ▄ ▄▄▄▄              ║
  ║                  █ █ █ █▄▄█ █ ▄▄ █▄▄█  ▄▄▀  █  █ █ █ █▄                ║
  ║                  █ █ █ █  █ █▄▄█ █  █ █▄▄▄ ▄█▄ █ █▄█ █▄▄▄              ║
  ║                                                                        ║
  ║                                                                        ║
  ║                                                                        ║
  ║            Copyright (c) 1992 by Tony Curro - All rights reserved.     ║
  ║                                                                        ║
  ║────────────────────────────────────────────────────────────────────────║
  ║ Volume I                  ■ Editor/Publisher ■            Number 5     ║
  ║ November                       Tony Curro                  1992        ║
  ╚════════════════════════════════════════════════════════════════════════╝
StoleYourWiFi:CTM9211 onixon$ cat CTMG

























                                                                                
  ╔════════════════════════════════════════════════════════════════════════╗
  ║                                                                        ║
  ║                 ▄▄▄▄ ▄▄▄▄ ▄▄▄▄▄ ▄▄▄▄ ▄  ▄ ▄▄▄▄▄ ▄▄▄▄ ▄▄▄▄              ║
  ║                 █    █  █ █ █ █ █▄▄█ █  █   █   █▄   █▄▄█              ║
  ║                 █▄▄▄ █▄▄█ █ █ █ █    █▄▄█   █   █▄▄▄ █ █▄              ║
  ║                           ▄▄▄▄▄ ▄▄▄▄ ▄    ▄ ▄▄                         ║
  ║                             █   █▄▄█ █    █▄█▄                         ║
  ║                             █   █  █ █▄▄▄ █  █ (tm)                    ║
  ║                  ▄▄▄▄▄ ▄▄▄▄ ▄▄▄▄ ▄▄▄▄ ▄▄▄▄ ▄▄▄ ▄▄▄ ▄ ▄▄▄▄              ║
  ║                  █ █ █ █▄▄█ █ ▄▄ █▄▄█  ▄▄▀  █  █ █ █ █▄                ║
  ║                  █ █ █ █  █ █▄▄█ █  █ █▄▄▄ ▄█▄ █ █▄█ █▄▄▄              ║
  ║                                                                        ║
  ║                                                                        ║
  ║                                                                        ║
  ║            Copyright (c) 1992 by Tony Curro - All rights reserved.     ║
  ║                                                                        ║
  ║────────────────────────────────────────────────────────────────────────║
  ║ Volume I                  ■ Editor/Publisher ■            Number 5     ║
  ║ November                       Tony Curro                  1992        ║
  ╚════════════════════════════════════════════════════════════════════════╝

                                                                                


              █         ▒▒▒▄                                      
              █        ▒■▒▒▒                       ░░░░░░░░░░░    
              █
        ▌▐▒▓▓ █         █▓▓▓ ▒░░░░░░░░░░░▒▒░  ░▒░▒░▒░░░░░░░░░░░░▒
              █       ▄█▓░░▒▒░░░░░░▒▒▒░░▓
▒▒▒▒▒░░░░░░░░░█      ▒█▒░░░░░░░░░░░░░░▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░    
              █        ▒░░░░░▒▒▒▒▒░▒▓▓▓▒▓▓▓▓▓▓░░░░░░░░░░░░░░      
              █
      ▓▓▒▒░░░░█    ▓▓▓▒▒░░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓░░░░░░░░░░░       
              █   ▒▒▓▒▒░░░░░░░▓▓▓▓▓▓▓▓▓▓▒▓▓▓▒▓▓▓░░░░░░░░░
              █  ▓▓▒▓▒▓░░░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▓▓▓▓▓░░░░░░           
              █  ▒▓░░░░░░░▒▓▓▒░░█▓▓▓▓▓▓▓▓▓▓▓▓▓▒▓▓▓░░░░            
              █   
▒▓▒▒▒▒▒▒▒▒░░░░█    ▓▓▓▓▓▓▓▓▓░░░░░░░░█▓▓▓▓▓▓▓▒▓▓▓▓▓▓▓░             
              █        ░░░░░░░░░░░░░░░░▓▓▓▓▓▓▓▓▒▒▓▓▓▒
        ┬ ┬ ┌─┐ ┌─┐┌─┐┬ ┬   ─┬─ ┬ ┬ ┌─┐ ┌┐┬ ┬┌  ┌─┐ ┌─┐ ┬ ┐ ┌ ┬ ┌┐┬ ┌─┐
        ├─┤ ├─┤ ├─┘├─┘└┬┘    │  ├─┤ ├─┤ │││ ├┴┐ └─┐ │ ┬ │ │ │ │ │││ │ ┬
        ┴ ┴ ┴ ┴ ┴  ┴   ┴     ┴  ┴ ┴ ┴ ┴ ┴└┘ ┴ ┴ └─┘ └─┘ ┴ └─┘ ┴ ┴└┘ └─┘
·■█                                                                           ■"...we are thankful that on this day we may pig-out without guilt."

StoleYourWiFi:CTM9211 onixon$ ls
ART1		ART15		ART4		ART7G		FILE_ID.DIZ
ART10           ART16           ART4G       ScreART8y Ansi AnticREADER.COM
ART11		ART17		ART5		ART8G		README.1ST
ART12		ART1G		ART5G		ART9		READROOM.TOC
ART13		ART2		ART6		ART9G
ART13G		ART3		ART6G		CTM
ART14		ART3G		ART7		CTMG
StoleYourWiFi:CTM9211 onixon$ clear

StoleYourWiFi:CTM9211 onixon$ ls
ART1		ART15		ART4		ART7G		FILE_ID.DIZ
ART10		ART16		ART4G		ART8		READER.COM
ART11		ART17		ART5		ART8G		README.1ST
ART12		ART1G		ART5G		ART9		READROOM.TOC
ART13		ART2		ART6		ART9G
ART13G		ART3		ART6G		CTM
ART14		ART3G		ART7		CTMG
StoleYourWiFi:CTM9211 onixon$ cat FILE_ID.DIZ
COMPUTERTALK(tm) MAGAZINE.
Volume I, Number 5 - November 1992.
A monthly online computer magazine with
articles, HW/SoftWare reviews, and news.
Uploaded by Editor/Publisher --- Tony
Curro. See README.1ST, in how to read
this magazine.
StoleYourWiFi:CTM9211 onixon$ cat ART1
                                  Welcome

                               by Tony Curro


        Another month has passed us by. We will be sitting down soon to
feast over a huge turkey, and to give thanks for all our blessings. I have
had some very pleasing news in the last few weeks. Microsoft was in contact
with me and is sending me a form to make me a beta site for MS products. I
was also contacted by Evelyn Hagfeldt who puts out a newsletter, Northland
Microcomputer Users Group. Evelyn sent me a message requesting to reprint
several of my articles in the newsletter. I received that newsletter on,
October 13. There is a possibility that she will reproduce other articles
that are of use to her group in future issues of the newsletter. Who knows?
Today a newsletter, tomorrow the WORLD!

        In addition our conference, "COMPTALK," is now being echoed by all
the boards that carry CatNET. SYSOPS who wish to be a part of CatNET,
please contact David Kaufman, SYSOP, Brooklyn Broadcasting, whose number
appears in my distribution list.

        I was talking to an associate of mine the other day who has shunned
Windows for quite some time. Recently he purchased a 486 system with 16MB
RAM. He tried Windows, and he was sold. He said that the Windows
counterparts, of the DOS programs he used to use, are easier to use in the
GUI (Graphical User Interface) environment. I must agree with him. I am a
lover of DESQview, DOS, and OS/2. I had shunned a mouse for quite some
time. Now I use the mouse most of the time. I do NOT think the GUI is the
wave of the future. GUI is the present. More and more applications are
moving to Windows and GUI. There is no getting around this. As a nay-sayer
of Windows, I will admit the GUI is here to stay.

        In the last few months, I have professed my dissatisfaction of
Windows. I still think more work needs to be done with the Windows
envioronment. I have used Windows since v1.3, and there have been
improvements. However, the programs that I have been seeing are making me
lean more towards Windows.

        Some of my readers may notice that I am doing more Windows reviews
each issue. For most prorgams, when I have a choice, I try to get a DOS
version. Most of the new releases, however, are Windows software. Since I
do want to review the latest version of the product, I get the Windows one.
This is turning me into a Windows freak.

        This month we have a article called NewsBytes. There are two bits
of information in there concerning the sale of Telix, and the HARSHER
penalties for software piracy. My thanks to Don Barba and Thomas Murphy,
for bringing this information to my attention.

        For starters, we are reviewing a program called InfoSelect for
Windows. InfoSelect has long been a favorite of an associate of mine. He
was using Tornado, made by the same company, before switching to
InfoSelect. He uses the DOS version. This new Windows version takes the DOS
version to new heights. Except for the typing, all of it can be controlled
by the mouse; from changing text colors to re-sizing windows; from saving
to cut and paste and so on. I think my associate may very well switch to
Windows now. When asked, more and more people say those three little
words: "I DO WINDOWS!" Many DOS programs, Norton Desktop for DOS and
PC-FILE to name just two, have a very similar GUI-type interface. In fact
Norton uses the same keystrokes in both the DOS and Windows versions of its
Desktop. Makes the switch to Windows much easier.

        I just got a press release about PC Tools v8.0 which should be
shipping by the time you read this. From the release it sounds very much
like Norton Desktop as far as changes in structure, and also in addition of
AntiVirus program and other features. It does bear repeating: "More and
more programs are trying to be Windows-like, even if you do not use that
environment.

        In addition to InfoSelect, we are taking a look at several other
Windows programs: Act!, Textor, Type Commander and MegaEdit (ShareWare).

        We are looking at two pieces of hardware this month. Zoom Fax/modem
and BackPack tape drive. In addition there is Qmodem and Links 386 Pro.


        Until next month, gobble up that turkey, and may all your bytes
count!

Tony Curro
StoleYourWiFi:CTM9211 onixon$ s -alrt
-bash: s: command not found
StoleYourWiFi:CTM9211 onixon$ ls -alrt
total 392
-rwxr-xr-x@   1 onixon  staff  14015 Jun  5  1992 READER.COM
-rwxr-xr-x@   1 onixon  staff   5619 Oct 23  1992 ART4
-rwxr-xr-x@   1 onixon  staff   5350 Oct 24  1992 ART14
-rwxr-xr-x@   1 onixon  staff    488 Oct 24  1992 READROOM.TOC
-rwxr-xr-x@   1 onixon  staff   3454 Oct 24  1992 ART11
-rwxr-xr-x@   1 onixon  staff    440 Oct 24  1992 ART12
-rwxr-xr-x@   1 onixon  staff   4363 Oct 25  1992 ART1
-rwxr-xr-x@   1 onixon  staff    111 Oct 27  1992 README.1ST
-rwxr-xr-x@   1 onixon  staff    243 Oct 27  1992 FILE_ID.DIZ
-rwxr-xr-x@   1 onixon  staff   3893 Oct 27  1992 CTMG
-rwxr-xr-x@   1 onixon  staff   1561 Oct 27  1992 CTM
-rwxr-xr-x@   1 onixon  staff   4384 Oct 27  1992 ART9G
-rwxr-xr-x@   1 onixon  staff   3930 Oct 27  1992 ART9
-rwxr-xr-x@   1 onixon  staff   3630 Oct 27  1992 ART8G
-rwxr-xr-x@   1 onixon  staff   3243 Oct 27  1992 ART8
-rwxr-xr-x@   1 onixon  staff   6813 Oct 27  1992 ART7G
-rwxr-xr-x@   1 onixon  staff   6005 Oct 27  1992 ART7
-rwxr-xr-x@   1 onixon  staff   4370 Oct 27  1992 ART6G
-rwxr-xr-x@   1 onixon  staff   3852 Oct 27  1992 ART6
-rwxr-xr-x@   1 onixon  staff   5212 Oct 27  1992 ART5G
-rwxr-xr-x@   1 onixon  staff   4634 Oct 27  1992 ART5
-rwxr-xr-x@   1 onixon  staff   6408 Oct 27  1992 ART4G
-rwxr-xr-x@   1 onixon  staff   7514 Oct 27  1992 ART3G
-rwxr-xr-x@   1 onixon  staff   6746 Oct 27  1992 ART3
-rwxr-xr-x@   1 onixon  staff   5191 Oct 27  1992 ART2
-rwxr-xr-x@   1 onixon  staff   4889 Oct 27  1992 ART1G
-rwxr-xr-x@   1 onixon  staff   1893 Oct 27  1992 ART17
-rwxr-xr-x@   1 onixon  staff    604 Oct 27  1992 ART16
-rwxr-xr-x@   1 onixon  staff   1371 Oct 27  1992 ART15
-rwxr-xr-x@   1 onixon  staff    844 Oct 27  1992 ART13G
-rwxr-xr-x@   1 onixon  staff    641 Oct 27  1992 ART13
-rwxr-xr-x@   1 onixon  staff   3827 Oct 27  1992 ART10
drwx------@  34 onixon  staff   1156 Feb 11 22:31 .
drwxr-xr-x+ 391 onixon  staff  13294 Feb 11 22:31 ..
StoleYourWiFi:CTM9211 onixon$ cat CTM
  ╔════════════════════════════════════════════════════════════════════════╗
  ║                                                                        ║
  ║                 ▄▄▄▄ ▄▄▄▄ ▄▄▄▄▄ ▄▄▄▄ ▄  ▄ ▄▄▄▄▄ ▄▄▄▄ ▄▄▄▄              ║
  ║                 █    █  █ █ █ █ █▄▄█ █  █   █   █▄   █▄▄█              ║
  ║                 █▄▄▄ █▄▄█ █ █ █ █    █▄▄█   █   █▄▄▄ █ █▄              ║
  ║                           ▄▄▄▄▄ ▄▄▄▄ ▄    ▄ ▄▄                         ║
  ║                             █   █▄▄█ █    █▄█▄                         ║
  ║                             █   █  █ █▄▄▄ █  █ (tm)                    ║
  ║                  ▄▄▄▄▄ ▄▄▄▄ ▄▄▄▄ ▄▄▄▄ ▄▄▄▄ ▄▄▄ ▄▄▄ ▄ ▄▄▄▄              ║
  ║                  █ █ █ █▄▄█ █ ▄▄ █▄▄█  ▄▄▀  █  █ █ █ █▄                ║
  ║                  █ █ █ █  █ █▄▄█ █  █ █▄▄▄ ▄█▄ █ █▄█ █▄▄▄              ║
  ║                                                                        ║
  ║                                                                        ║
  ║                                                                        ║
  ║            Copyright (c) 1992 by Tony Curro - All rights reserved.     ║
  ║                                                                        ║
  ║────────────────────────────────────────────────────────────────────────║
  ║ Volume I                  ■ Editor/Publisher ■            Number 5     ║
  ║ November                       Tony Curro                  1992        ║
  ╚════════════════════════════════════════════════════════════════════════╝
StoleYourWiFi:CTM9211 onixon$ ls
ART1		ART15		ART4		ART7G		FILE_ID.DIZ
ART10		ART16		ART4G		ART8		READER.COM
ART11		ART17		ART5		ART8G		README.1ST
ART12		ART1G		ART5G		ART9		READROOM.TOC
ART13		ART2		ART6		ART9G
ART13G		ART3		ART6G		CTM
ART14		ART3G		ART7		CTMG
StoleYourWiFi:CTM9211 onixon$ scp * root@modernpascal.com:/var/LEGACYX/GENERAL/
root@modernpascal.com's password: 
ART1                                          100% 4363     4.3KB/s   00:00    
ART10                                         100% 3827     3.7KB/s   00:00    
ART11                                         100% 3454     3.4KB/s   00:00    
ART12                                         100%  440     0.4KB/s   00:00    
ART13                                         100%  641     0.6KB/s   00:00    
ART13G                                        100%  844     0.8KB/s   00:00    
ART14                                         100% 5350     5.2KB/s   00:00    
ART15                                         100% 1371     1.3KB/s   00:00    
ART16                                         100%  604     0.6KB/s   00:00    
ART17                                         100% 1893     1.9KB/s   00:00    
ART1G                                         100% 4889     4.8KB/s   00:00    
ART2                                          100% 5191     5.1KB/s   00:00    
ART3                                          100% 6746     6.6KB/s   00:00    
ART3G                                         100% 7514     7.3KB/s   00:00    
ART4                                          100% 5619     5.5KB/s   00:00    
ART4G                                         100% 6408     6.3KB/s   00:00    
ART5                                          100% 4634     4.5KB/s   00:00    
ART5G                                         100% 5212     5.1KB/s   00:00    
ART6                                          100% 3852     3.8KB/s   00:00    
ART6G                                         100% 4370     4.3KB/s   00:00    
ART7                                          100% 6005     5.9KB/s   00:00    
ART7G                                         100% 6813     6.7KB/s   00:00    
ART8                                          100% 3243     3.2KB/s   00:00    
ART8G                                         100% 3630     3.5KB/s   00:00    
ART9                                          100% 3930     3.8KB/s   00:00    
ART9G                                         100% 4384     4.3KB/s   00:00    
CTM                                           100% 1561     1.5KB/s   00:00    
CTMG                                          100% 3893     3.8KB/s   00:00    
FILE_ID.DIZ                                   100%  243     0.2KB/s   00:00    
READER.COM                                    100%   14KB  13.7KB/s   00:00    
README.1ST                                    100%  111     0.1KB/s   00:00    
READROOM.TOC                                  100%  488     0.5KB/s   00:00    
StoleYourWiFi:CTM9211 onixon$ vim CTM
StoleYourWiFi:CTM9211 onixon$ scp CTM root@modernpascal.com:/var/LEGACYX/GENERAL/
root@modernpascal.com's password: 
CTM                                           100% 1340     1.3KB/s   00:00    
StoleYourWiFi:CTM9211 onixon$ tcpdump -en
tcpdump: ioctl(SIOCIFCREATE): Operation not permitted
StoleYourWiFi:CTM9211 onixon$ sudo bash
Password:
bash-3.2# tcpdump en0
tcpdump: data link type PKTAP
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on pktap, link-type PKTAP (Packet Tap), capture size 262144 bytes
^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel
bash-3.2# ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=3<RXCSUM,TXCSUM>
	inet6 ::1 prefixlen 128 
	inet 127.0.0.1 netmask 0xff000000 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=27<RXCSUM,TXCSUM,VLAN_MTU,TSO4>
	ether 00:25:00:db:1f:4c 
	inet6 fe80::225:ff:fedb:1f4c%en0 prefixlen 64 scopeid 0x4 
	inet 169.254.50.101 netmask 0xffff0000 broadcast 169.254.255.255
	nd6 options=1<PERFORMNUD>
	media: autoselect (1000baseT <full-duplex,flow-control>)
	status: active
en1: flags=8823<UP,BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	ether 00:25:00:42:86:f4 
	nd6 options=1<PERFORMNUD>
	media: autoselect (<unknown type>)
	status: inactive
fw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 4078
	lladdr 00:25:00:ff:fe:db:1f:4c 
	nd6 options=1<PERFORMNUD>
	media: autoselect <full-duplex>
	status: inactive
p2p0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 2304
	ether 02:25:00:42:86:f4 
	media: autoselect
	status: inactive
vmnet1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 00:50:56:c0:00:01 
	inet 192.168.245.1 netmask 0xffffff00 broadcast 192.168.245.255
vmnet8: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 00:50:56:c0:00:08 
	inet 192.168.112.1 netmask 0xffffff00 broadcast 192.168.112.255
bash-3.2# tcpdump en0 -vv
tcpdump: data link type PKTAP
tcpdump: listening on pktap, link-type PKTAP (Packet Tap), capture size 262144 bytes
tcpdump: pktap_filter_packet: pcap_add_if_info(en0, 1) failed: pcap_add_if_info: pcap_compile_nopcap() failed
bash-3.2# tcpdump en0 
tcpdump: data link type PKTAP
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on pktap, link-type PKTAP (Packet Tap), capture size 262144 bytes
tcpdump: pktap_filter_packet: pcap_add_if_info(vmnet1, 1) failed: pcap_add_if_info: pcap_compile_nopcap() failed
bash-3.2# tcpdump en0 
tcpdump: data link type PKTAP
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on pktap, link-type PKTAP (Packet Tap), capture size 262144 bytes
tcpdump: pktap_filter_packet: pcap_add_if_info(en0, 1) failed: pcap_add_if_info: pcap_compile_nopcap() failed
bash-3.2# 
  [Restored May 5, 2020, 2:12:54 PM]
Last login: Tue May  5 14:12:50 on ttys002
StoleYourWiFi:CTM9211 onixon$ 
  [Restored Sep 6, 2020, 1:44:56 PM]
Last login: Sun Sep  6 13:44:55 on ttys002
StoleYourWiFi:CTM9211 onixon$ 
  [Restored Feb 2, 2021, 7:23:25 PM]
Last login: Tue Feb  2 19:23:23 on ttys002
StoleYourWiFi:CTM9211 onixon$ cd
StoleYourWiFi:~ onixon$ cd Downloads/
StoleYourWiFi:Downloads onixon$ ls
$RECYCLE.BIN
2002V103.ZIP
30-daySat.jpg
3tier.gif
500ter.zip
ACRO151.ZIP
AFDEV431.ZIP
AGTSRC(1).ZIP
AGTSRC.ZIP
ANSWCODE.ZIP
ASC2PAS.ZIP
AVTS11.ZIP
AdobeFlashPlayer_19_a_install.dmg
AdobeFlashPlayer_32_a_install.dmg
Advanced_TCP_IP.pdf
BBSCHAT.ZIP
BPDOOM.ZIP
BPOS.ZIP
BSPTREE.ZIP
BULL.ZIP
BattleShip-master
BattleShip-master.zip
Booot_5_1_0_source
Booot_5_1_0_source.rar
Borm 10-23F.mp4
Brave-Browser-QUK420.pkg
BrowsersProjects.zip
CALYR2.ZIP
CBASIC_Compiler_CB86_Programmers_Guide_May83.pdf
CBM64W
CBM64W.ZIP
CSYS14.ZIP
CTM9211
CTM9211.ZIP
CentOS-6.10-i386-bin-DVD1.iso
CentOS-6.10-i386-bin-DVD2.iso
CentOS-7-x86_64-DVD-1804.iso
CodeTyphonIns
Compiler
Compiler.zip
CreativeCloudInstaller.dmg
D2DOOM.ZIP
DDPLUS67.ZIP
DOS71CD.ISO
DOSBox-0.74-2_Universal.dmg
DP2TP.ZIP
DRLM21.ZIP
Digital Research CBASIC-86 Compiler 2.0 for MS-DOS
Digital Research CBASIC-86 Compiler 2.0 for MS-DOS.7z
DomainDownloadList-271005535.csv
DomainDownloadList-271005595.csv.gz
Driver Packet 2019.pdf
EKEYS11B.ZIP
ELECOM13
EMSI.ZIP
EXchess_v7.71
Elsinore.ScreenConnect.Client.zip
Elsinore.ScreenConnect.ClientSetup(1).pkg
Elsinore.ScreenConnect.ClientSetup-1.pkg
Elsinore.ScreenConnect.ClientSetup.pkg
Ent
EtherTerm-master.zip
FIDO (JPEG Image, 247┬á├ù┬á300 pixels).jpg
FINPUT.ZIP
FORUM25C.ZIP
FR41059A.dst
FR41059A.pes
FR41059A.xxx
FR41060A.dst
FR41060A.pes
FR41060A.xxx
Facebook Hack and How It Affects You-1.docx
Facebook Hack and How It Affects You.docx
Fav.jpg
Firefox 40.0.3.dmg
Firefox 41.0.dmg
FlashPascal
FreeRTOSV8.2.3
FreeRTOSV8.2.3.zip
FundamentalsCipher407.zip
GS130224.ZIP
GS7615ST.ZIP
Game-master
Gizmic OS 0.03.rar
Green.png
HACK
HACK.zip
HCN305.ZIP
HEAP7.PAS
HERBALIFE.ai.ps
HOB100.ZIP
HelloWorld
IFP1S156.ZIP
INDUCE.ZIP
IVS - My Account.html
IVS - My Account2.html
IVS - My Account2_files
IVS - My Account_files
Install Spotify.app
InstallSQLiteStudio-3.2.1.dmg
JNTP1SM.ZIP
LAZARUS
LTCOMM50.ZIP
LZH_PAS.ZIP
LZSFX.ZIP
MADTRB1.ZIP
MADTRB10.ZIP
MADTRB11.ZIP
MADTRB12.ZIP
MADTRB13.ZIP
MADTRB14.ZIP
MADTRB15.ZIP
MADTRB16.ZIP
MADTRB17.ZIP
MADTRB18.ZIP
MADTRB19.ZIP
MADTRB2.ZIP
MADTRB20.ZIP
MADTRB21.ZIP
MADTRB28.ZIP
MADTRB29.ZIP
MADTRB3.ZIP
MADTRB30(1).ZIP
MADTRB30.ZIP
MADTRB31.ZIP
MADTRB32.ZIP
MADTRB33.ZIP
MADTRB34.ZIP
MADTRB35.ZIP
MADTRB36.ZIP
MADTRB37.ZIP
MADTRB38.ZIP
MADTRB39.ZIP
MADTRB4.ZIP
MADTRB40.ZIP
MADTRB5.ZIP
MADTRB7.ZIP
MADTRB8.ZIP
MADTRB9.ZIP
MADTURBO.ZIP
MNG132.ZIP
MOCK_DATA(1).csv
MOCK_DATA(2).csv
MOCK_DATA.csv
Mastermind-master
NERDBOWL.ZIP
NOTE20.ZIP
NUM_RECI.ZIP
NexusDBV3.pdf
NexusDBV3_PDF_2009_03_10.zip
NexusDB_V4.5005_Standard_Edition.exe
NexusDB_V4.5005_Standard_Edition.zip
Norm 10-23 G.mp4
ODBC.ZIP
OpenXP5.0.34-win.zip
Optimized Internet Solutions - Quotes for Dante.docx
P063B907
P063B907.ZIP
P063S907.ZIP
PARSCL.PAS
PASEDIT.ZIP
PAS_DEMO.ZIP
PAVT
PAVT150.ZIP
PCBoardv16WebLogoLG.png
PCBoardv16WebLogoLGTransparant.png
PCL4P42.ZIP
POWRDOOR.ZIP
PROK3055.ZIP
PSGUI130.ZIP
PSLST100.ZIP
PSPPD100.ZIP
PSSTK101.ZIP
PSSTR102.ZIP
PabloDrawMac-3.2.1
PabloDrawMac-3.2.1.zip
Paintbrush-2.5.0.zip
ParallelsDesktop-11.0.1-31277.dmg
Pascal_2019-3859.zip
Pascal_Language_Ref.pdf
PhoneGapDesktop-2.dmg
PhoneGapDesktop.dmg
QWRIT11.ZIP
README.ans
RGREC.ZIP
RLE.PAS
RMDOOR30.ZIP
RebornModernPascal.ans
SAURON_S.ZIP
SENDMAIL.ZIP
SIPInside.0.3.0.zip
SQLite4Delphi-0
SWTIP.ZIP
ScreenConnect Client.app
SheepShaver_2.5_20190504.zip
SpotifyInstaller.zip
Sub Lease.doc
Sublease Contract Template-Blank.doc
SwiftLink-232-application-notes-(revised).pdf
SyncTERM.dmg
TICTAC.ZIP
TI_PAS1.ZIP
TI_PAS2.ZIP
TI_PAS3.ZIP
TMODEM.ZIP
TOOL-INC.ZIP
TOP15.ZIP
TPCM9407.ZIP
TPHYD100.ZIP
TSPA3370.ZIP
TURKIT01.ZIP
TWARS(1).ZIP
TWARS.ZIP
TeamViewer.dmg
TheUnarchiver.dmg
UCF-T4KY.ZIP
USING.ZIP
UTIL178.ZIP
Untitled-3(1).png
Untitled-3(2).png
Untitled-3.jpg
Untitled-3.png
VMware-Fusion-10.1.6-12989998.dmg
VMware-Fusion-11.0.0-10120384.dmg
VMware-Fusion-11.0.2-10952296.dmg
VMware-Fusion-11.0.3-12992109.dmg
VMware-Fusion-11.1.1-14328561.dmg
VMware-Fusion-8.0.0-2985594.dmg
VMware-Player-12.0.0-2985596.x86_64.bundle
VMware-player-12.0.0-2985596.exe
VirtualBox-5.0.4-102546-OSX.dmg
WEDITS22.ZIP
WINDOB10.ZIP
WPExport.zip
WW4BIN61.ZIP
WXMOPAS.ZIP
White.png
XiiD-IM.docx
YAK18B.ZIP
ZPASCAL.ZIP
ZTELSRV.ZIP
aesource
aesource.zip
aspell-0.60.8.tar.gz
atp08src.zip
basic.shar
basic.shar.Z
brev988.exe
cat80src.zip
cel204r
cel204r.zip
cevodelphiaikit
cevosrc
cheng4
chessx-1.3.2.dmg
ckcnet.c
cpm3src
cpm3src 2
cpm3src.tgz
cpm3src.zip
cpmdate.pas
crashmail-1.7
crashmail-1.7.zip
cxc_legacyxbbs2020_newheader(1).ans
cxc_legacyxbbs2020_newheader.ans
dejal-generic-utils-srcs.bin
desktop.ini
dhtmlxScheduler_v37_win_130220.zip
emsi.arj
exachess-lite-402.dmg
f2i200.exe
fastix3c.zip
fmp_trial_fm_14.0.2.200.dmg
fms_trial_14.0.3.302.dmg
fpc-3.0.4
fpc-3.0.4.powerpc-macosx.dmg
fpc-3.0.4a.intel-macosx(1).dmg
fpc-3.0.4a.intel-macosx.dmg
fpcbuild-3.0.4
fpcbuild-3.0.4.zip
fpcjvmmacosx-snapshot-20130906.tbz
fpos-c387b381d7a0
gvsg2102.zip
hedgewars-src-0.9.21.1.tar.bz2
hello.c
htscreen.zip
index.txt
inter61a
inter61a.zip
intrfc63
intrfc63.zip
jedit5.5.0install.dmg
jmodem-master
kbmMW5_06_20_Ent_Setup 2 2.zip
kbmMW5_06_20_Ent_Setup 2.zip
kbmMW5_06_20_Ent_Setup.zip
kbmMemTablePro_78010_Setup.zip
kbmSQLiteMan_170
kbmSQLiteMan_170.zip
lape-bug_fixes.zip
lape-master.zip
lazarus-1.8.4-fpc-3.0.4-win64.exe
lazarus-2.0.4-i686-macosx.dmg
library
library.zip
m p.png
mfsrc130.zip
middleware.png
midware
midware.zip
modern-pascal-logo.png
modern-pascal-png.png
modern.jpg
mrec1072
msg0002.WAV
msgapi38.zip
msq310.zip
mtask20.zip
mygate06.zip
nasm-2.14rc15-dos-upx.zip
nxpascal-master
openxp-5.0.34-1.i586-linux.zip
openxp-5.0.34.src.zip
pascal_gui
pascal_gui.zip
pased11.zip
pibter41
pibter41.zip
ppl4p10
ppl4p10 2
ppl4p10.zip
procps-3.2.8
procps-3.2.8.tar
prokit
prot018s
prot018s.arj
prot100
prot100.zip
protobuf-delphi-1.1.zip
qodem-1.0.0.dmg
qodem-master.zip
qp.zip
ra_262sw.zip
rbcom346.zip
rzsztp00
rzsztp00.zip
sauron-0.4.1.1
sauron-0.4.1.1-src.tar.gz
sbbs1173
sbbs1173.zip
sealink-master
sine.pas
slide_5.jpg
sre0994b.zip
stockfish-6-mac
stockfish-6-mac.zip
swapunt7
swapunt7.zip
test.p
th.jpg
tp301a.tgz
tppopups
tppopups.zip
tpslink
tpslink.zip
tpv24.zip
tpzmodem
tpzmodem.zip
tpznewg.zip
tpzsfz
tpzsfz.zip
trial_extfs.dmg
tttdem51.zip
tttdoc51.zip
tttsrc51.zip
turbopascal-master.zip
tw2002v103
tw40
tw40.zip
unarj-221.hqx
unarj-221.hqx 2.cpgz
unarj-221.hqx.cpgz
upnpresources.zip
userlist.ans
www-developip-com.pdf
wxmodem-master
xbbsos2.zip
xdp
zmax-master
StoleYourWiFi:Downloads onixon$ ping 192.168.10.254
PING 192.168.10.254 (192.168.10.254): 56 data bytes
64 bytes from 192.168.10.254: icmp_seq=0 ttl=63 time=5.350 ms
64 bytes from 192.168.10.254: icmp_seq=1 ttl=63 time=4.304 ms
64 bytes from 192.168.10.254: icmp_seq=2 ttl=63 time=4.236 ms
64 bytes from 192.168.10.254: icmp_seq=3 ttl=63 time=2.610 ms
^C
--- 192.168.10.254 ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 2.610/4.125/5.350/0.980 ms
StoleYourWiFi:Downloads onixon$ ping 192.168.10.253
PING 192.168.10.253 (192.168.10.253): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
92 bytes from 192.168.10.250: Destination Host Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 d16b   0 0000  3f  01 1c3e 192.168.1.178  192.168.10.253 

92 bytes from 192.168.10.250: Destination Host Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 b103   0 0000  3f  01 3ca6 192.168.1.178  192.168.10.253 

92 bytes from 192.168.10.250: Destination Host Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 0cdf   0 0000  3f  01 e0ca 192.168.1.178  192.168.10.253 

Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
92 bytes from 192.168.10.250: Destination Host Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 f23c   0 0000  3f  01 fb6c 192.168.1.178  192.168.10.253 

92 bytes from 192.168.10.250: Destination Host Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 4f56   0 0000  3f  01 9e53 192.168.1.178  192.168.10.253 

92 bytes from 192.168.10.250: Destination Host Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 cb15   0 0000  3f  01 2294 192.168.1.178  192.168.10.253 

^C
--- 192.168.10.253 ping statistics ---
7 packets transmitted, 0 packets received, 100.0% packet loss
StoleYourWiFi:Downloads onixon$ scp 192.168.10.254:~/Documents/VID10* .
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:kpiKX/NiFNbQ0yvjq0Dw6FU2YaY57+/3rOuZbkGDyrk.
Please contact your system administrator.
Add correct host key in /Users/onixon/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/onixon/.ssh/known_hosts:2
ECDSA host key for 192.168.10.254 has changed and you have requested strict checking.
Host key verification failed.
StoleYourWiFi:Downloads onixon$ rm -rf ../.ssh/known_hosts 
StoleYourWiFi:Downloads onixon$ scp 192.168.10.254:~/Documents/VID10* .
The authenticity of host '192.168.10.254 (192.168.10.254)' can't be established.
ECDSA key fingerprint is SHA256:kpiKX/NiFNbQ0yvjq0Dw6FU2YaY57+/3rOuZbkGDyrk.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.10.254' (ECDSA) to the list of known hosts.
Password:
VID10.m4v                                     100% 1325MB   1.2MB/s   17:57    
StoleYourWiFi:Downloads onixon$ df -h
Filesystem      Size   Used  Avail Capacity  iused    ifree %iused  Mounted on
/dev/disk0s2   446Gi  328Gi  118Gi    74% 85995470 31007512   73%   /
devfs          179Ki  179Ki    0Bi   100%      620        0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%        0        0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%        0        0  100%   /home
StoleYourWiFi:Downloads onixon$ scp 192.168.10.254:~/Documents/VID? .
Password:
scp: /Users/onixon/Documents/VID?: No such file or directory
StoleYourWiFi:Downloads onixon$ scp 192.168.10.254:~/Documents/VID?.* .
Password:
VID1.m4v                                      100%  425MB   2.9MB/s   02:25    
VID2.m4v                                      100%  446MB   2.6MB/s   02:55    
VID3.m4v                                      100%  768MB   2.7MB/s   04:46    
VID4.m4v                                      100%  393MB   2.9MB/s   02:14    
VID5.m4v                                      100%  624MB   2.7MB/s   03:49    
VID6.m4v                                      100%  668MB   2.6MB/s   04:17    
VID7.m4v                                      100%  463MB   2.7MB/s   02:55    
VID8.m4v                                      100%   32MB   3.2MB/s   00:10    
VID9.m4v                                      100%  225MB   2.4MB/s   01:32    
StoleYourWiFi:Downloads onixon$ 
  [Restored Mar 18, 2021, 6:22:05 PM]
Last login: Thu Mar 18 18:22:04 on ttys002
StoleYourWiFi:Downloads onixon$ 
  [Restored May 7, 2021, 7:19:25 PM]
Last login: Sun Apr 18 06:25:38 on console
StoleYourWiFi:Downloads onixon$ pwd
/Users/onixon/Downloads
StoleYourWiFi:Downloads onixon$ 
  [Restored Sep 13, 2021, 7:45:49 PM]
Last login: Mon Sep 13 19:45:49 on ttys002
StoleYourWiFi:Downloads onixon$ 
  [Restored Sep 17, 2021, 8:27:15 PM]
Last login: Fri Sep 17 20:27:14 on ttys002
StoleYourWiFi:Downloads onixon$ cd /source
StoleYourWiFi:source onixon$ ls
ADBV15				WWIVEdit-master
ANSI				WebApp
Addict3				XP-BBS
AresRegular246_082217		argus
BBS				battleship
BigTable			bitmaps
Compression.jpg			bpdx_old
DATABASE			bulletins
DOS				classes
DOS33_SOURCE			cms
FAT32				exchange
FSE				fasthtmlparser-0.4-delphi
FTSC				fpc_test
FroDo				games
Gunshot-master			gnutella
LAZARUS				htmlparser
LVCL				mp3
MPMOS				mpsolutions
MoriaOP-master			nasm-2.14rc15
Northwind			premiercubes
OpenXP				rubicon
QuickLink			scripts
RG119SRC-master			softnet
SG				tpclone
TORO				vidgui
TRS80				vpascal
Thumbs.db			vpascal.install
UTIL-SHELL-DOS-Navigator-master	water
Usurper-master			websocket
VTXEdit-master
StoleYourWiFi:source onixon$ cd bpdx
-bash: cd: bpdx: No such file or directory
StoleYourWiFi:source onixon$ cd mp3/bpdx
StoleYourWiFi:bpdx onixon$ scp root@modernpascal.com:/source/dxdataset/XMLIni.pas .
root@modernpascal.com's password: 
XMLIni.pas                                    100%   47KB  46.6KB/s   00:00    
StoleYourWiFi:bpdx onixon$ ls
1				dxutil_crt.pas
1.pp				dxutil_environment.o
3.3				dxutil_environment.pas
BPDX_v6.zip			dxutil_environment.ppu
FastMM4.pas			dxutil_gui.pas
FastMM4Messages.pas		dxutil_hash.o
FastMM4Messages.ppu		dxutil_hash.pas
FastMM4Options.inc		dxutil_hash.ppu
MD2.dpr				dxutil_internet.o
MD4.dpr				dxutil_internet.pas
MD5.dpr				dxutil_internet.ppu
MemCheck.pas			dxutil_logging.o
README.txt			dxutil_logging.pas
RIPE128.dpr			dxutil_logging.ppu
RIPE160.dpr			dxutil_numeric.o
RIPE256.dpr			dxutil_numeric.pas
SHA1.dpr			dxutil_numeric.ppu
STRUCT.290			dxutil_objectpool.pas
Tiger128.dpr			dxutil_quicksort.o
Tiger160.dpr			dxutil_quicksort.pas
Tiger192.dpr			dxutil_quicksort.ppu
XMLIni.pas			dxutil_string.o
dxarpping.pas			dxutil_string.pas
dxbasictimer.pas		dxutil_string.ppu
dxcachedflexiblelogging.pas	dxutil_threads.o
dxcachedlogging.pas		dxutil_threads.pas
dxdnsquery.pas			dxutil_threads.ppu
dxping.o			dxutil_timer.o
dxping.pas			dxutil_timer.pas
dxping.ppu			dxutil_timer.ppu
dxprot_xmodem.pas		format
dxsock6.bu			hheapman.pas
dxsock6.o			libimpdxsock6.a
dxsock6.pas			libimpdxutil_classes.a
dxsock6.ppu			libimpdxutil_environment.a
dxsock6.rsj			pingexample.pas
dxsock6.rst			resource_english.inc
dxsock_ftpserver.pas		resource_french.inc
dxsock_genericserver.o		resource_german.inc
dxsock_genericserver.pas	resource_indonesian.inc
dxsock_genericserver.ppu	resource_italian.inc
dxsock_openssl.pas		resource_lowmem.inc
dxsock_pop3server.pas		resource_portuguese.inc
dxsock_smtpserver.pas		resource_russian.inc
dxsqlite3.pas			resource_spanish.inc
dxutil_balancedtree.pas		resource_turkish.inc
dxutil_bufferedio.pas		test
dxutil_cachearray.o		test.cfg
dxutil_cachearray.pas		test.dof
dxutil_cachearray.ppu		test.dpr
dxutil_cipher.o			test.pp
dxutil_cipher.pas		test1.pp
dxutil_cipher.ppu		test2
dxutil_classes.o		test2.pp
dxutil_classes.pas		testping
dxutil_classes.ppu		testping.dpr
dxutil_common.o			testudpscan
dxutil_common.pas		testudpscan.pp
dxutil_common.ppu		unix_os.pas
StoleYourWiFi:bpdx onixon$ ls dxutil*pas
dxutil_balancedtree.pas	dxutil_crt.pas		dxutil_numeric.pas
dxutil_bufferedio.pas	dxutil_environment.pas	dxutil_objectpool.pas
dxutil_cachearray.pas	dxutil_gui.pas		dxutil_quicksort.pas
dxutil_cipher.pas	dxutil_hash.pas		dxutil_string.pas
dxutil_classes.pas	dxutil_internet.pas	dxutil_threads.pas
dxutil_common.pas	dxutil_logging.pas	dxutil_timer.pas
StoleYourWiFi:bpdx onixon$ grep GMT dxutil*.pas
dxutil_environment.pas:function DateTimeToGMT(const DT:TDateTime):TDateTime;
dxutil_environment.pas:function DateTimeToGMTRFC822(const DT:TDateTime):string;
dxutil_environment.pas:function DateTimeToGMT(const DT:TDateTime):TDateTime;
dxutil_environment.pas:function DateTimeToGMTRFC822(const DT:TDateTime):string;
dxutil_environment.pas:   Result:=FormatDateTime('ddd, dd mmm yyyy hh:nn:ss',DateTimeToGMT(DT))+' GMT';
StoleYourWiFi:bpdx onixon$ vim dxutil_internet.pas
StoleYourWiFi:bpdx onixon$ cd /source/LAZARUS/PSQLClient/
StoleYourWiFi:PSQLClient onixon$ ls
PSQLClient		PSQLClient.lps		ucredentials.pas
PSQLClient.app		PSQLClient.res		umainform.lfm
PSQLClient.ico		backup			umainform.pas
PSQLClient.lpi		lib
PSQLClient.lpr		ucredentials.lfm
StoleYourWiFi:PSQLClient onixon$ cd PSQLClient.app/Contents/MacOS/
StoleYourWiFi:MacOS onixon$ ls
PSQLClient	PSQLClient.xml
StoleYourWiFi:MacOS onixon$ cat PSQLClient.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!-- Generator: TDXXMLINI 2.0 site="www.bpdx.com" -->
<TDXXMLINI>
</TDXXMLINI>
StoleYourWiFi:MacOS onixon$ cat PSQLClient.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!-- Generator: TDXXMLINI 2.0 site="www.bpdx.com" -->
<TDXXMLINI>
</TDXXMLINI>
StoleYourWiFi:MacOS onixon$ cat PSQLClient.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!-- Generator: TDXXMLINI 2.0 site="www.bpdx.com" -->
<TDXXMLINI>
	<Credentials>
		<RememberMe>true</RememberMe>
		<AutoConnect>true</AutoConnect>
		<UserName>OZZ</UserName>
		<Password>PASSWORD</Password>
		<Server>dante.modernpascal.com</Server>
	</Credentials>
</TDXXMLINI>
StoleYourWiFi:MacOS onixon$ cd /source
StoleYourWiFi:source onixon$ ls mp3
-y					lpexceptions.o
1.1					lpexceptions.pas
100doorsOpt.px				lpexceptions.ppu
2.2					lpinterpreter.000
Common.inc				lpinterpreter.o
FasterMM.pas				lpinterpreter.pas
IMS.DB					lpinterpreter.ppu
LICENSE.SQZ				lpmessages.000
MAINBRD.jdt				lpparser.000
MAINBRD.jdx				lpparser.o
MAINBRD.jhr				lpparser.pas
MAINBRD.jlr				lpparser.ppu
MP1191229.ZIP				lptree.000
Options.inc				lptree.o
OverideOverloadedMethod.lap		lptree.pas
README.md				lptree.ppu
STSystem.inc				lptypes.000
SelfTest.pas				lptypes.bak
_lpgenerateevalfunctions.pas		lptypes.o
ansi-color-chart.sh			lptypes.pas
arc.p					lptypes.ppu
arrayaccess.p				lputils.pas
basicexample.p				lpvartypes.000
bbking_string_gauge.txt			lpvartypes.o
bench.p					lpvartypes.pas
bench.py				lpvartypes.ppu
bench2.p				lpvartypes_array.o
benchtest.p				lpvartypes_array.pas
binkd.inc				lpvartypes_array.ppu
binkd.p					lpvartypes_ord.o
binkp_client.pas			lpvartypes_ord.pas
binkp_globals.inc			lpvartypes_ord.ppu
binkp_parse_opt.inc			lpvartypes_record.o
binkp_pkt_naming.inc			lpvartypes_record.pas
blank.p					lpvartypes_record.ppu
bools.p					main.lfm
bpdx					main.pas
bufds.db				makepdf.p
bufdstest.p				makeproduction
bufread.p				math101.p
bug001.p				mathgame.p
buildallcoderunner			memds.db
buildallcoderunner110			memdstest.p
buildallproduction			memtrace.log
buildallproduction110			mimic.p
buildcoderunner				mixed.p
buildcoderunnerdebug			mod_celerity.pp
builddebug				mod_mp2.pp
buildlape				mp2
buildmodule22				mp2.dpr
buildmodule24				mp2.dsk
buildproduction				mp2.exe
buildspellproduction			mp2.o
buildsslcoderunner			mp2.pp
buildsslproduction			mp2.upx
buildstamp.i				mp2_32bit.tgz
buildstamp.p				mp2_all
chain1.p				mp2_bare
chain2.p				mp2_spell
chain3.p				mp2_ssl
cmsreport.inc				mp2gui
cnames.p				mp2gui.ico
coderunner2				mp2gui.lpi
coderunner2.exe				mp2gui.lps
coderunner2.pp				mp2gui.pp
coderunner2_64bit.tgz			mp2gui.res
coderunner2_bare			nada.p
coderunner2_ssl				nada.px
coderunner_ssl_aspell_debian_x64.tar.gz	nestedfunc.p
coderunner_ssl_aspell_rhel_x64.tar.gz	newreport.pdf
dbisam					nntpproxy
dbisam4					not.p
delayed.txt				ord64.p
descendanttest.p			ozz.log
dijkstras.p				pcbwfc.p
dlltest					pidtest.p
domains.lst				ppaslink.sh
dummy.$$$				r.p
empty					renpkt.p
empty.p					restaurants.txt
enumtest.p				rtest.p
fortest					rubyexample.p
fortest.p				s.p
fp.cfg					sa.p
fp.dsk					scripts
fp.ini					search.p
funcs.p					set.p
genfile.p				settest.p
guitake2.p				socketraw.p
guitest.p				speedometer.p
halcyon					splicing.p
henricorestaurants.db3			sql3test.db3
httpd_mod_celerity.conf.example		sql3test.p
ifopt.p					sshtest.p
import_bbk.p				systest.p
includes				t.p
keys.p					t1.p
lessons					t2.p
libmod_mp2.so				test
lic.p					test.p
link.res				test.pdf
listreport.pdf				test.pp
loot.p					test102.p
lpclasshelper.o				test3.pas
lpclasshelper.pas			testhint.p
lpclasshelper.ppu			testrandom.p
lpcodeemitter.000			testreport.pdf
lpcodeemitter.o				testreport_uncompressed.pdf
lpcodeemitter.pas			tosser
lpcodeemitter.ppu			u.p
lpcompiler.000				units
lpcompiler.o				utf8.p
lpcompiler.pas				v.p
lpcompiler.ppu				violations.txt
lpdisassembler.pas			w.p
lpeval.000				x.p
lpeval.o				xnum.p
lpeval.pas				xset.p
lpeval.ppu				y.p
StoleYourWiFi:source onixon$ cd mp3/bpdx/
StoleYourWiFi:bpdx onixon$ ls XML*
XMLIni.pas
StoleYourWiFi:bpdx onixon$ ping dante.modernpascal.com
PING dante.modernpascal.com (38.17.55.2): 56 data bytes
64 bytes from 38.17.55.2: icmp_seq=0 ttl=114 time=69.126 ms
64 bytes from 38.17.55.2: icmp_seq=1 ttl=114 time=63.549 ms
64 bytes from 38.17.55.2: icmp_seq=2 ttl=114 time=69.164 ms
^C
--- dante.modernpascal.com ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 63.549/67.280/69.164/2.638 ms
StoleYourWiFi:bpdx onixon$ cd /source/mp3/units/
StoleYourWiFi:units onixon$ ls
1.1				compress.o
4096.txt.bz2			compress.pas
AMFOSSIL.PAS			crypt.o
AMFOSSIL.TPU			crypt.pas
DXBFILE.PAS			crypt.ppu
DXBFILE.o			crypter.pas
DXBFILE.ppu			ds_export_xls.o
DXDATE.PAS			ds_export_xls.pas
DXDATE.o			ds_export_xls.ppu
DXDATE.ppu			ds_export_xml.o
DXFILE.PAS			ds_export_xml.pas
DXFILE.o			ds_export_xml.ppu
DXFILE.ppu			fidoopus.pas
DXJAM.PAS			full_macbeth.html
DXJAM.o				gateone-1.1-1.noarch.rpm
DXJAM.ppu			janSQL.o
DXSDM.PAS			janSQL.pas
FILE_ID.DIZ			janSQL.ppu
HTDEMO.PAS			janSQLExpression2.o
HTINPUT.PAS			janSQLExpression2.pas
HTINPUT.o			janSQLExpression2.ppu
HTINPUT.ppu			janSQLStrings.o
HTSCREEN.PAS			janSQLStrings.pas
HTSCREEN.o			janSQLStrings.ppu
HTSCREEN.ppu			janSQLTokenizer.o
HTSTRING.PAS			janSQLTokenizer.pas
HTSTRING.o			janSQLTokenizer.ppu
HTSTRING.ppu			jansql-master.zip
JAMCRC32.PAS			lh5
JAMCRC32.o			lh5.o
JAMCRC32.ppu			lh5.pas
JAMINFO.PAS			lh5.ppu
JsonAlchemy.o			lhsix.o
JsonAlchemy.pas			lhsix.pas
JsonAlchemy.ppu			lhsix.ppu
PdfDoc.o			lz.o
PdfDoc.pas			lz.pas
PdfDoc.ppu			lz.ppu
PdfFonts.o			lzw.o
PdfFonts.pas			lzw.pas
PdfFonts.ppu			lzw.ppu
PdfGBFonts.pas			makefile.p
PdfImages.pas			memcheck.pas
PdfJPFonts.pas			mpripemd160.o
PdfJpCMap.pas			mpripemd160.pas
PdfJpegImage.pas		mpripemd160.ppu
PdfTypes.o			mpsha1.o
PdfTypes.pas			mpsha1.pas
PdfTypes.ppu			mpsha1.ppu
UUDECODE.PAS			mpsha256.o
UUDECODE.exe			mpsha256.pas
UUENCODE.PAS			mpsha256.ppu
UUENCODE.exe			mwStringHashList.o
UUSOURCE.DOC			mwStringHashList.pas
archive.arj			mwStringHashList.ppu
archive.tar.gz			phpfox_92078c-3.7.4.zip
archive.wet			shrink.pp
balancedtrees.o			synlz.o
balancedtrees.pas		synlz.pas
balancedtrees.ppu		synlz.ppu
bighuff.o			test.zip
bighuff.pas			testcompress.p
bighuff.ppu			testcomptime.p
bitsequence.o			tmp
bitsequence.pas			uMQTT.pas
bitsequence.ppu			uMQTType.pas
btmp				wetvd_poc.p
calcexpress.o			zipstrprocs.o
calcexpress.pas			zipstrprocs.pas
calcexpress.ppu			zipstrprocs.ppu
compress
StoleYourWiFi:units onixon$ vim synlz.pas
StoleYourWiFi:units onixon$ cd /source/LAZARUS/
StoleYourWiFi:LAZARUS onixon$ ls
ANSIScreen		LearningComponents	UDAFAN
AlmostOnLine		MPSEmail		addons
CodeEditor		PSQLClient		learn
CustomMicroSolutions14	PSQLClient.zip		learnTChart
DXMotherboard		Plugins			project1.ico
FolderSynchronizer	Rhenium			project1.lpi
FormDesigner		SQLite3Tool		project1.lpr
HTMLReader		Take3			project1.lps
LearnDBControls		TheDrawModern
StoleYourWiFi:LAZARUS onixon$ ls -alrt
total 8400
drwxr-xr-x  57 onixon  wheel     1938 Sep 29  2018 addons
drwxr-xr-x  13 onixon  wheel      442 Sep 29  2018 FolderSynchronizer
drwxr-xr-x  16 onixon  wheel      544 Sep 29  2018 AlmostOnLine
drwxr-xr-x  14 onixon  wheel      476 Sep 29  2018 SQLite3Tool
drwxr-xr-x  15 onixon  wheel      510 Sep 29  2018 LearningComponents
drwxr-xr-x   2 onixon  wheel       68 Sep 29  2018 Take3
-rw-r--r--   1 onixon  wheel      868 Sep 29  2018 project1.lps
-rw-r--r--   1 onixon  wheel      369 Sep 29  2018 project1.lpr
-rw-r--r--   1 onixon  wheel     1855 Sep 29  2018 project1.lpi
-rw-r--r--   1 onixon  wheel   137040 Sep 29  2018 project1.ico
drwxr-xr-x  30 onixon  wheel     1020 Sep 29  2018 Rhenium
drwxr-xr-x  16 onixon  wheel      544 Sep 29  2018 HTMLReader
drwxr-xr-x  10 onixon  wheel      340 Sep 29  2018 FormDesigner
drwxr-xr-x  10 onixon  wheel      340 Sep 29  2018 DXMotherboard
drwxr-xr-x  10 onixon  wheel      340 Sep 29  2018 learnTChart
drwxr-xr-x   5 onixon  wheel      170 Sep 29  2018 learn
drwxr-xr-x  12 onixon  wheel      408 Sep 29  2018 TheDrawModern
drwxr-xr-x  95 onixon  wheel     3230 Sep 29  2018 ANSIScreen
drwxr-xr-x  16 onixon  wheel      544 Sep 29  2018 Plugins
drwxr-xr-x  15 onixon  wheel      510 Sep 29  2018 MPSEmail
drwxr-xr-x  16 onixon  wheel      544 Oct  3  2018 UDAFAN
drwxr-xr-x  25 onixon  wheel      850 Oct 19  2018 CustomMicroSolutions14
drwxr-xr-x  18 onixon  wheel      612 Oct 26  2018 LearnDBControls
drwxr-xr-x  10 onixon  wheel      340 Sep  1  2019 CodeEditor
drwxr-xr-x  62 onixon  wheel     2108 Jan 30  2020 ..
drwxr-xr-x  16 onixon  wheel      544 Sep 21 23:14 PSQLClient
drwxr-xr-x  28 onixon  wheel      952 Sep 22 17:05 .
-rw-r--r--   1 onixon  wheel  4148050 Sep 22 17:05 PSQLClient.zip
StoleYourWiFi:LAZARUS onixon$ scp PSQLClient.zip root@modernpascal.com:/source/
root@modernpascal.com's password: 
PSQLClient.zip                                100% 4051KB   2.0MB/s   00:02    
StoleYourWiFi:LAZARUS onixon$ cd
StoleYourWiFi:~ onixon$ cd Downloads/
StoleYourWiFi:Downloads onixon$ ls -alrt
total 44376320
-rw-r--r--@   1 onixon  staff      257156 Aug  2  2000 qp.zip
drwxr-xr-x@ 156 onixon  staff        5304 Sep  3  2008 sauron-0.4.1.1
-rw-r--r--@   1 onixon  staff     2893398 Dec  4  2008 Gizmic OS 0.03.rar
-rwxr-xr-x@   1 onixon  staff    14214319 Mar 10  2009 NexusDBV3.pdf
-rw-r--r--@   1 onixon  staff     4124556 May 27  2010 exachess-lite-402.dmg
drwxr-xr-x@   9 onixon  staff         306 Jun 11  2011 Mastermind-master
-rw-r--r--@   1 onixon  staff       84480 Jan 15  2012 Sublease Contract Template-Blank.doc
-rw-r--r--@   1 onixon  staff      138269 Mar 30  2012 Booot_5_1_0_source.rar
drwxr-xr-x@   5 onixon  staff         170 Jun 16  2013 Game-master
-rw-r--r--@   1 onixon  staff        5564 Aug 31  2014 FR41059A.xxx
-rw-r--r--@   1 onixon  staff        5706 Aug 31  2014 FR41059A.dst
-rw-r--r--@   1 onixon  staff       11726 Aug 31  2014 FR41059A.pes
-rw-r--r--@   1 onixon  staff        6632 Aug 31  2014 FR41060A.xxx
-rw-r--r--@   1 onixon  staff       14813 Aug 31  2014 FR41060A.pes
-rw-r--r--@   1 onixon  staff        7308 Aug 31  2014 FR41060A.dst
-rw-r--r--@   1 onixon  staff       59004 Oct 16  2014 White.png
-rw-r--r--@   1 onixon  staff       58154 Oct 16  2014 Green.png
-rw-r--r--@   1 onixon  staff      906058 Oct 23  2014 HERBALIFE.ai.ps
-rw-r--r--@   1 onixon  staff   160250791 Jan  6  2015 hedgewars-src-0.9.21.1.tar.bz2
-rw-r--r--@   1 onixon  staff    38820085 Feb 23  2015 PhoneGapDesktop.dmg
-rw-r--r--@   1 onixon  staff    23733362 May  5  2015 chessx-1.3.2.dmg
drwxr-xr-x@   9 onixon  staff         306 Jun 12  2015 nxpascal-master
-rw-r--r--@   1 onixon  staff   440553376 Aug 14  2015 fmp_trial_fm_14.0.2.200.dmg
-rw-r--r--@   1 onixon  staff    72872096 Aug 15  2015 VMware-player-12.0.0-2985596.exe
-rw-r--r--@   1 onixon  staff   138882307 Aug 15  2015 VMware-Player-12.0.0-2985596.x86_64.bundle
-rw-r--r--@   1 onixon  staff   379261403 Aug 15  2015 VMware-Fusion-8.0.0-2985594.dmg
-rw-r--r--@   1 onixon  staff      760444 Aug 24  2015 AdobeFlashPlayer_19_a_install.dmg
-rw-r--r--@   1 onixon  staff    77397467 Aug 26  2015 Firefox 40.0.3.dmg
-rw-r--r--@   1 onixon  staff   303469260 Sep  8  2015 ParallelsDesktop-11.0.1-31277.dmg
-rw-r--r--@   1 onixon  staff   333483581 Sep 11  2015 fms_trial_14.0.3.302.dmg
-rw-r--r--@   1 onixon  staff    44504301 Sep 16  2015 PhoneGapDesktop-2.dmg
-rw-------    1 onixon  staff           0 Sep 16  2015 .localized
-rw-r--r--@   1 onixon  staff    78862787 Sep 17  2015 Firefox 41.0.dmg
drwx------@   9 onixon  staff         306 Sep 17  2015 CodeTyphonIns
-rw-r--r--@   1 onixon  staff     1661015 Sep 18  2015 CreativeCloudInstaller.dmg
-rw-r--r--@   1 onixon  staff       56320 Sep 18  2015 Sub Lease.doc
-rw-r--r--    1 onixon  staff     9455616 Sep 21  2015 DOS71CD.ISO
-rw-r--r--@   1 onixon  staff           0 Sep 22  2015 Optimized Internet Solutions - Quotes for Dante.docx
-rw-r--r--@   1 onixon  staff      396634 Sep 24  2015 dhtmlxScheduler_v37_win_130220.zip
-rw-r--r--@   1 onixon  staff      103878 Sep 24  2015 www-developip-com.pdf
-rw-r--r--@   1 onixon  staff      116939 Oct  1  2015 MOCK_DATA.csv
-rw-r--r--@   1 onixon  staff      114183 Oct  1  2015 MOCK_DATA(1).csv
-rw-r--r--@   1 onixon  staff      107693 Oct  2  2015 MOCK_DATA(2).csv
-rw-r--r--    1 onixon  staff        6546 Oct  2  2015 test.p
-rw-r--r--@   1 onixon  staff       53710 Oct  2  2015 index.txt
-rw-r--r--@   1 onixon  staff    90403064 Oct  2  2015 VirtualBox-5.0.4-102546-OSX.dmg
-rw-r--r--@   1 onixon  staff        1223 Oct  3  2015 DomainDownloadList-271005595.csv.gz
-rw-r--r--@   1 onixon  staff       22971 Oct  3  2015 DomainDownloadList-271005535.csv
-rw-r--r--@   1 onixon  staff      167921 Oct  3  2015 FundamentalsCipher407.zip
-rw-r--r--@   1 onixon  staff       19172 Oct  3  2015 protobuf-delphi-1.1.zip
-rw-r--r--@   1 onixon  staff     1024000 Oct  7  2015 procps-3.2.8.tar
drwxr-xr-x@  53 onixon  staff        1802 Oct  7  2015 procps-3.2.8
drwx------@  12 onixon  staff         408 Oct  7  2015 FlashPascal
-rw-r--r--@   1 onixon  staff       70375 Oct  7  2015 30-daySat.jpg
drwx------@   5 onixon  staff         170 Oct  9  2015 cevosrc
drwx------@  16 onixon  staff         544 Oct  9  2015 cevodelphiaikit
drwxr-xr-x   13 onixon  staff         442 Oct  9  2015 fpos-c387b381d7a0
drwx------@  30 onixon  staff        1020 Oct  9  2015 ppl4p10
drwx------@   4 onixon  staff         136 Oct  9  2015 mrec1072
drwxr-xr-x@   5 onixon  staff         170 Oct  9  2015 sealink-master
drwxr-xr-x@   6 onixon  staff         204 Oct  9  2015 zmax-master
drwx------@  11 onixon  staff         374 Oct 10  2015 SQLite4Delphi-0
-rw-r--r--@   1 onixon  staff    33801528 Oct 12  2015 HACK.zip
drwx------@  33 onixon  staff        1122 Oct 12  2015 HACK
-rw-r--r--@   1 onixon  staff     1574368 Oct 13  2015 BattleShip-master.zip
drwxr-xr-x@  41 onixon  staff        1394 Oct 13  2015 BattleShip-master
drwxr-xr-x@  16 onixon  staff         544 Oct 17  2015 cheng4
drwxrwxr-x@  15 onixon  staff         510 Oct 17  2015 EXchess_v7.71
drwxr-xr-x    5 onixon  staff         170 Oct 17  2015 Booot_5_1_0_source
-rw-r--r--@   1 onixon  staff      613900 Oct 24  2015 stockfish-6-mac.zip
drwxr-xr-x@   8 onixon  staff         272 Oct 24  2015 stockfish-6-mac
-rw-r--r--@   1 onixon  staff      907904 Dec  3  2015 lape-master.zip
-rw-r--r--@   1 onixon  staff      914335 Dec  3  2015 lape-bug_fixes.zip
-rw-r--r--@   1 onixon  staff       32721 Dec 19  2015 th.jpg
-rw-r--r--@   1 onixon  staff     5123729 Jan 29  2016 sauron-0.4.1.1-src.tar.gz
-rw-r--r--@   1 onixon  staff      880137 Jan 30  2016 ACRO151.ZIP
-rw-r--r--@   1 onixon  staff      427978 Jan 30  2016 DRLM21.ZIP
-rw-r--r--@   1 onixon  staff      925018 Jan 30  2016 GS7615ST.ZIP
-rw-r--r--@   1 onixon  staff      117373 Jan 30  2016 JNTP1SM.ZIP
-rw-r--r--@   1 onixon  staff      130490 Jan 30  2016 SAURON_S.ZIP
-rw-r--r--@   1 onixon  staff    10397741 Jan 30  2016 GS130224.ZIP
-rw-r--r--@   1 onixon  staff     1042699 Jan 30  2016 WW4BIN61.ZIP
-rw-r--r--@   1 onixon  staff      535482 Jan 30  2016 YAK18B.ZIP
-rw-r--r--@   1 onixon  staff      140322 Jan 30  2016 ZTELSRV.ZIP
-rw-r--r--@   1 onixon  staff      517243 Feb  5  2016 cat80src.zip
-rw-r--r--@   1 onixon  staff      110652 Feb  5  2016 fastix3c.zip
-rw-r--r--@   1 onixon  staff      337980 Feb  5  2016 brev988.exe
-rw-r--r--@   1 onixon  staff      310660 Feb  5  2016 sre0994b.zip
-rw-r--r--@   1 onixon  staff      163036 Feb  5  2016 turbopascal-master.zip
-rw-r--r--@   1 onixon  staff       57260 Feb  5  2016 CBM64W.ZIP
drwxr-xr-x@  18 onixon  staff         612 Feb  5  2016 CBM64W
-rw-r--r--@   1 onixon  staff       15967 Feb  5  2016 ZPASCAL.ZIP
-rw-r--r--@   1 onixon  staff       35039 Feb  5  2016 SENDMAIL.ZIP
-rw-r--r--@   1 onixon  staff      296106 Feb  5  2016 SIPInside.0.3.0.zip
-rw-r--r--@   1 onixon  staff       97121 Feb  5  2016 BPDOOM.ZIP
-rw-r--r--@   1 onixon  staff      195181 Feb  5  2016 D2DOOM.ZIP
-rw-r--r--@   1 onixon  staff      136708 Feb  5  2016 BSPTREE.ZIP
-rw-r--r--@   1 onixon  staff      578992 Feb  6  2016 pibter41.zip
drwx------@   8 onixon  staff         272 Feb  6  2016 pibter41
-rw-r--r--@   1 onixon  staff       58072 Feb  6  2016 Compiler.zip
drwx------@  12 onixon  staff         408 Feb  6  2016 Compiler
-rw-r--r--@   1 onixon  staff     1062042 Feb  6  2016 cpm3src.tgz
drwx------@   7 onixon  staff         238 Feb  6  2016 cpm3src
-rw-r--r--@   1 onixon  staff      991952 Feb  6  2016 cpm3src.zip
drwxr-xr-x@   8 onixon  staff         272 Feb  6  2016 cpm3src 2
-rw-r--r--@   1 onixon  staff       73326 Feb  6  2016 tp301a.tgz
-rw-r--r--@   1 onixon  staff        9626 Feb  6  2016 cpmdate.pas
-rw-r--r--@   1 onixon  staff        1991 Feb  6  2016 sine.pas
-rw-r--r--@   1 onixon  staff    45117268 Feb  6  2016 FreeRTOSV8.2.3.zip
drwxr-xr-x@  10 onixon  staff         340 Feb  6  2016 FreeRTOSV8.2.3
-rw-r--r--@   1 onixon  staff        3909 Feb  6  2016 emsi.arj
-rw-r--r--@   1 onixon  staff       65428 Feb  6  2016 unarj-221.hqx
-rw-r--r--    1 onixon  staff       49772 Feb  6  2016 unarj-221.hqx.cpgz
-rw-r--r--    1 onixon  staff       49770 Feb  6  2016 unarj-221.hqx 2.cpgz
-rw-r--r--@   1 onixon  staff        7572 Feb  6  2016 library.zip
drwx------@   6 onixon  staff         204 Feb  6  2016 library
-rw-r--r--@   1 onixon  staff       38347 Feb  6  2016 aesource.zip
drwx------@  18 onixon  staff         612 Feb  6  2016 aesource
-rw-r--r--@   1 onixon  staff       54855 Feb  6  2016 basic.shar.Z
-rw-r--r--@   1 onixon  staff    12264065 Feb  7  2016 fpcjvmmacosx-snapshot-20130906.tbz
-rw-r--r--@   1 onixon  staff     1037510 Feb  7  2016 xbbsos2.zip
-rw-r--r--@   1 onixon  staff      239932 Feb  7  2016 msgapi38.zip
-rw-r--r--@   1 onixon  staff      455636 Feb  7  2016 msq310.zip
-rw-r--r--@   1 onixon  staff       46584 Feb  7  2016 mygate06.zip
-rw-r--r--@   1 onixon  staff      264005 Feb  7  2016 atp08src.zip
-rw-r--r--@   1 onixon  staff       68233 Feb  7  2016 mfsrc130.zip
-rw-r--r--@   1 onixon  staff       12198 Feb  7  2016 RGREC.ZIP
-rw-r--r--@   1 onixon  staff      228940 Feb  8  2016 EtherTerm-master.zip
-rw-r--r--@   1 onixon  staff     5844897 Feb  8  2016 qodem-master.zip
-rw-r--r--@   1 onixon  staff    69115257 Feb  8  2016 upnpresources.zip
-rw-r--r--@   1 onixon  staff      227456 Feb  8  2016 dejal-generic-utils-srcs.bin
-rw-r--r--@   1 onixon  staff     2642027 Feb  8  2016 Pascal_Language_Ref.pdf
-rw-r--r--@   1 onixon  staff      169796 Feb 11  2016 basic.shar
-rw-r--r--@   1 onixon  staff      120809 Feb 14  2016 rbcom346.zip
-rw-r--r--@   1 onixon  staff      360590 Feb 14  2016 inter61a.zip
drwx------@  18 onixon  staff         612 Feb 14  2016 inter61a
-rw-r--r--@   1 onixon  staff         285 Feb 15  2016 hello.c
-rw-r--r--@   1 onixon  staff    17210516 Feb 16  2016 Elsinore.ScreenConnect.ClientSetup.pkg
-rw-r--r--@   1 onixon  staff    17097523 Feb 17  2016 Elsinore.ScreenConnect.Client.zip
drwxr-xr-x@   3 onixon  staff         102 Feb 17  2016 ScreenConnect Client.app
-rw-r--r--@   1 onixon  staff    25504273 Feb 24  2016 TeamViewer.dmg
drwxr-xr-x   37 onixon  staff        1258 Feb 24  2016 IVS - My Account_files
-rw-r--r--@   1 onixon  staff       16588 Feb 24  2016 IVS - My Account.html
drwxr-xr-x   36 onixon  staff        1224 Feb 24  2016 IVS - My Account2_files
-rw-r--r--@   1 onixon  staff       21671 Feb 24  2016 IVS - My Account2.html
-rw-r--r--@   1 onixon  staff   519549556 Sep 27  2018 VMware-Fusion-11.0.0-10120384.dmg
drwxr-xr-x@   7 onixon  staff         238 Sep 27  2018 wxmodem-master
drwxr-xr-x@   6 onixon  staff         204 Sep 27  2018 jmodem-master
-rw-r--r--@   1 onixon  staff  4470079488 Sep 27  2018 CentOS-7-x86_64-DVD-1804.iso
-rw-r--r--@   1 onixon  staff  3870294016 Sep 27  2018 CentOS-6.10-i386-bin-DVD1.iso
-rw-r--r--@   1 onixon  staff  1394278400 Sep 27  2018 CentOS-6.10-i386-bin-DVD2.iso
drwxr-xr-x   11 onixon  staff         374 Sep 28  2018 LAZARUS
drwxr-xr-x@   3 onixon  staff         102 Sep 28  2018 $RECYCLE.BIN
-rw-r--r--@   1 onixon  staff   153726305 Sep 28  2018 lazarus-1.8.4-fpc-3.0.4-win64.exe
-rw-r--r--@   1 onixon  staff       38800 Sep 29  2018 msg0002.WAV
-rw-rw-rw-@   1 onixon  staff     4179686 Sep 29  2018 DOSBox-0.74-2_Universal.dmg
-rw-rw-rw-@   1 onixon  staff    28305758 Sep 29  2018 trial_extfs.dmg
-rw-r--r--@   1 onixon  staff      240636 Sep 29  2018 crashmail-1.7.zip
drwxr-xr-x@  11 onixon  staff         374 Sep 29  2018 crashmail-1.7
-rw-r--r--@   1 onixon  staff     2751026 Sep 29  2018 openxp-5.0.34-1.i586-linux.zip
-rw-r--r--@   1 onixon  staff     3236243 Sep 29  2018 OpenXP5.0.34-win.zip
-rw-r--r--@   1 onixon  staff     8257883 Sep 29  2018 openxp-5.0.34.src.zip
-rw-r--r--@   1 onixon  staff     5035202 Sep 29  2018 jedit5.5.0install.dmg
-rw-r--r--@   1 onixon  staff     1286875 Sep 29  2018 nasm-2.14rc15-dos-upx.zip
-rw-r--r--@   1 onixon  staff       13922 Oct  1  2018 XiiD-IM.docx
-rw-r--r--@   1 onixon  staff   108371671 Oct  2  2018 fpc-3.0.4a.intel-macosx.dmg
-rwxr-xr-x@   1 onixon  staff         282 Oct  2  2018 desktop.ini
-rw-r--r--@   1 onixon  staff    26688655 Oct  4  2018 InstallSQLiteStudio-3.2.1.dmg
-rw-r--r--@   1 onixon  staff       13922 Oct  5  2018 Facebook Hack and How It Affects You.docx
-rw-r--r--@   1 onixon  staff      849012 Oct  6  2018 ra_262sw.zip
-rw-r--r--@   1 onixon  staff       19822 Oct  6  2018 mtask20.zip
-rw-r--r--@   1 onixon  staff      753922 Oct  6  2018 sbbs1173.zip
drwx------@  22 onixon  staff         748 Oct  6  2018 sbbs1173
-rw-r--r--@   1 onixon  staff       28952 Oct  6  2018 swapunt7.zip
drwx------@  14 onixon  staff         476 Oct  6  2018 swapunt7
-rw-r--r--@   1 onixon  staff     1978824 Oct  6  2018 cel204r.zip
drwx------@  14 onixon  staff         476 Oct  6  2018 cel204r
-rw-r--r--@   1 onixon  staff        4806 Oct  6  2018 tpv24.zip
-rw-r--r--@   1 onixon  staff       14138 Oct  7  2018 Facebook Hack and How It Affects You-1.docx
-rw-r--r--@   1 onixon  staff       15575 Oct  8  2018 tppopups.zip
drwx------@   6 onixon  staff         204 Oct  8  2018 tppopups
-rw-r--r--@   1 onixon  staff      117107 Oct  8  2018 pased11.zip
-rw-r--r--@   1 onixon  staff       44413 Oct  8  2018 htscreen.zip
-rw-r--r--@   1 onixon  staff       85619 Oct  8  2018 tttsrc51.zip
-rw-r--r--@   1 onixon  staff       63298 Oct  8  2018 tttdem51.zip
-rw-r--r--@   1 onixon  staff       44205 Oct  8  2018 tttdoc51.zip
-rwxr-xr-x@   1 onixon  staff    10440256 Oct 12  2018 NexusDB_V4.5005_Standard_Edition.exe
-rw-rw-rw-@   1 onixon  staff       14684 Oct 16  2018 FIDO (JPEG Image, 247┬á├ù┬á300 pixels).jpg
-rw-rw-rw-@   1 onixon  staff       35765 Oct 17  2018 Untitled-3.png
-rw-rw-rw-@   1 onixon  staff       50224 Oct 17  2018 Untitled-3.jpg
-rw-rw-rw-@   1 onixon  staff     1265555 Oct 17  2018 modern.jpg
-rw-rw-rw-@   1 onixon  staff     1801613 Oct 17  2018 Fav.jpg
-rw-rw-rw-@   1 onixon  staff       54933 Oct 17  2018 BrowsersProjects.zip
drwx------@   8 onixon  staff         272 Oct 17  2018 HelloWorld
-rw-rw-rw-@   1 onixon  staff       41535 Oct 17  2018 Untitled-3(1).png
-rw-rw-rw-@   1 onixon  staff      103256 Oct 17  2018 modern-pascal-logo.png
-rw-rw-rw-@   1 onixon  staff      585202 Oct 17  2018 modern-pascal-png.png
-rw-rw-rw-@   1 onixon  staff       55154 Oct 17  2018 Untitled-3(2).png
-rw-rw-rw-@   1 onixon  staff      260405 Oct 18  2018 m p.png
-rw-rw-rw-@   1 onixon  staff     2858318 Oct 19  2018 kbmSQLiteMan_170.zip
drwx------@   5 onixon  staff         170 Oct 19  2018 kbmSQLiteMan_170
-rw-rw-rw-@   1 onixon  staff    30816183 Oct 19  2018 kbmMW5_06_20_Ent_Setup.zip
-rw-rw-rw-@   1 onixon  staff    30816183 Oct 19  2018 kbmMW5_06_20_Ent_Setup 2.zip
-rw-rw-rw-@   1 onixon  staff    30816183 Oct 19  2018 kbmMW5_06_20_Ent_Setup 2 2.zip
-rw-rw-rw-@   1 onixon  staff     1675608 Oct 19  2018 kbmMemTablePro_78010_Setup.zip
drwxr-xr-x    2 onixon  staff          68 Oct 19  2018 Ent
-rw-rw-rw-@   1 onixon  staff      717224 Oct 20  2018 midware.zip
drwx------@  12 onixon  staff         408 Oct 20  2018 midware
-rw-rw-rw-@   1 onixon  staff        6994 Oct 23  2018 middleware.png
-rw-rw-rw-@   1 onixon  staff        5642 Oct 23  2018 3tier.gif
-rw-rw-rw-@   1 onixon  staff       94545 Oct 23  2018 slide_5.jpg
-rw-rw-rw-@   1 onixon  staff     3226127 Oct 24  2018 Norm 10-23 G.mp4
-rw-rw-rw-@   1 onixon  staff     3354304 Oct 24  2018 Borm 10-23F.mp4
-rw-rw-rw-@   1 onixon  staff    10363883 Oct 25  2018 NexusDB_V4.5005_Standard_Edition.zip
-rw-rw-rw-@   1 onixon  staff    17210505 Oct 26  2018 Elsinore.ScreenConnect.ClientSetup(1).pkg
-rw-rw-rw-@   1 onixon  staff    12256143 Oct 27  2018 NexusDBV3_PDF_2009_03_10.zip
drwxr-xr-x@   3 onixon  staff         102 May  3  2019 Install Spotify.app
-rw-r--r--@   1 onixon  staff    98748823 May 17  2019 fpc-3.0.4.powerpc-macosx.dmg
-rw-r--r--@   1 onixon  staff      770586 May 19  2019 SpotifyInstaller.zip
-rw-r--r--@   1 onixon  staff        4874 Aug 10  2019 RebornModernPascal.ans
-rw-r--r--@   1 onixon  staff     1000634 Aug 10  2019 Advanced_TCP_IP.pdf
-rw-r--r--@   1 onixon  staff   519261989 Aug 11  2019 VMware-Fusion-11.1.1-14328561.dmg
-rw-r--r--@   1 onixon  staff   519579915 Aug 11  2019 VMware-Fusion-11.0.3-12992109.dmg
-rw-r--r--@   1 onixon  staff   519474715 Aug 11  2019 VMware-Fusion-11.0.2-10952296.dmg
-rw-r--r--@   1 onixon  staff   465655417 Aug 11  2019 VMware-Fusion-10.1.6-12989998.dmg
-rw-r--r--@   1 onixon  staff      336606 Aug 18  2019 f2i200.exe
-rw-r--r--@   1 onixon  staff     1443402 Aug 18  2019 500ter.zip
-rw-r--r--@   1 onixon  staff       37272 Aug 18  2019 UCF-T4KY.ZIP
-rw-rw-rw-@   1 onixon  staff    11173888 Aug 19  2019 SyncTERM.dmg
-rw-rw-rw-@   1 onixon  staff    14129268 Aug 19  2019 TheUnarchiver.dmg
-rw-rw-rw-@   1 onixon  staff      168295 Aug 19  2019 prot018s.arj
drwxr-xr-x   13 onixon  staff         442 Aug 19  2019 prot018s
-rw-rw-rw-@   1 onixon  staff       38762 Aug 19  2019 prot100.zip
drwx------@  15 onixon  staff         510 Aug 19  2019 prot100
-rw-rw-rw-@   1 onixon  staff       26795 Aug 19  2019 rzsztp00.zip
drwx------@  16 onixon  staff         544 Aug 19  2019 rzsztp00
-rw-rw-rw-@   1 onixon  staff        6261 Aug 19  2019 tpslink.zip
drwx------@   5 onixon  staff         170 Aug 19  2019 tpslink
-rw-rw-rw-@   1 onixon  staff       51335 Aug 19  2019 tpzmodem.zip
drwx------@  20 onixon  staff         680 Aug 19  2019 tpzmodem
-rw-rw-rw-@   1 onixon  staff       34569 Aug 19  2019 tpznewg.zip
-rw-rw-rw-@   1 onixon  staff       22623 Aug 19  2019 tpzsfz.zip
drwx------@  10 onixon  staff         340 Aug 19  2019 tpzsfz
-rw-rw-rw-@   1 onixon  staff     2755797 Aug 20  2019 Driver Packet 2019.pdf
-rw-rw-rw-@   1 onixon  staff      240141 Aug 20  2019 PAVT150.ZIP
drwxr-xr-x   31 onixon  staff        1054 Aug 21  2019 PAVT
-rw-rw-rw-@   1 onixon  staff       14724 Aug 21  2019 PCBoardv16WebLogoLGTransparant.png
-rw-rw-rw-@   1 onixon  staff       38953 Aug 21  2019 PCBoardv16WebLogoLG.png
-rw-rw-rw-@   1 onixon  staff       48097 Aug 28  2019 ckcnet.c
drwx------@  24 onixon  staff         816 Aug 29  2019 ELECOM13
drwxr-xr-x@   9 onixon  staff         306 Aug 29  2019 xdp
-rw-rw-rw-@   1 onixon  staff     4820988 Aug 29  2019 PabloDrawMac-3.2.1.zip
drwx------@   4 onixon  staff         136 Aug 29  2019 PabloDrawMac-3.2.1
-rw-rw-rw-@   1 onixon  staff      121005 Aug 31  2019 tw40.zip
drwx------@   6 onixon  staff         204 Aug 31  2019 tw40
-rw-rw-rw-@   1 onixon  staff      506011 Aug 31  2019 2002V103.ZIP
drwxr-xr-x   14 onixon  staff         476 Aug 31  2019 tw2002v103
-rw-rw-rw-@   1 onixon  staff   201250589 Aug 31  2019 lazarus-2.0.4-i686-macosx.dmg
-rw-rw-rw-@   1 onixon  staff   108371671 Aug 31  2019 fpc-3.0.4a.intel-macosx(1).dmg
drwxr-xr-x@  16 onixon  staff         544 Sep  1  2019 fpc-3.0.4
-rw-rw-rw-@   1 onixon  staff    76407145 Sep  1  2019 fpcbuild-3.0.4.zip
drwxr-xr-x@  10 onixon  staff         340 Sep  1  2019 fpcbuild-3.0.4
-rw-rw-rw-@   1 onixon  staff      240268 Sep  2  2019 AGTSRC.ZIP
-rw-rw-rw-@   1 onixon  staff       38854 Sep  2  2019 SWTIP.ZIP
-rw-rw-rw-@   1 onixon  staff       34817 Sep  2  2019 TPCM9407.ZIP
-rw-rw-rw-@   1 onixon  staff       47269 Sep  2  2019 CSYS14.ZIP
-rw-rw-rw-@   1 onixon  staff      156193 Sep  2  2019 DDPLUS67.ZIP
-rw-rw-rw-@   1 onixon  staff       40488 Sep  2  2019 UTIL178.ZIP
-rw-rw-rw-@   1 onixon  staff      125614 Sep  2  2019 IFP1S156.ZIP
-rw-rw-rw-@   1 onixon  staff       15132 Sep  2  2019 ANSWCODE.ZIP
-rw-rw-rw-@   1 onixon  staff       17379 Sep  2  2019 BBSCHAT.ZIP
-rw-rw-rw-@   1 onixon  staff       90630 Sep  2  2019 LTCOMM50.ZIP
-rw-rw-rw-@   1 onixon  staff       30221 Sep  2  2019 NOTE20.ZIP
-rw-rw-rw-@   1 onixon  staff       13624 Sep  2  2019 PASEDIT.ZIP
-rw-rw-rw-@   1 onixon  staff        9868 Sep  2  2019 WXMOPAS.ZIP
-rw-rw-rw-@   1 onixon  staff       12258 Sep  2  2019 BULL.ZIP
-rw-rw-rw-@   1 onixon  staff      188621 Sep  2  2019 FORUM25C.ZIP
-rw-rw-rw-@   1 onixon  staff      115759 Sep  2  2019 PROK3055.ZIP
-rw-rw-rw-@   1 onixon  staff      113577 Sep  2  2019 TOOL-INC.ZIP
-rw-rw-rw-@   1 onixon  staff      100265 Sep  2  2019 TOP15.ZIP
-rw-rw-rw-@   1 onixon  staff       62978 Sep  2  2019 TWARS.ZIP
-rw-rw-rw-@   1 onixon  staff       75815 Sep  2  2019 TWARS(1).ZIP
-rw-rw-rw-@   1 onixon  staff      323992 Sep  2  2019 HCN305.ZIP
-rw-rw-rw-@   1 onixon  staff       14744 Sep  2  2019 CALYR2.ZIP
-rw-rw-rw-@   1 onixon  staff       12785 Sep  3  2019 DP2TP.ZIP
-rw-rw-rw-@   1 onixon  staff       66600 Sep  3  2019 INDUCE.ZIP
-rw-rw-rw-@   1 onixon  staff       76380 Sep  3  2019 MADTRB1.ZIP
-rw-rw-rw-@   1 onixon  staff       92796 Sep  3  2019 MADTRB10.ZIP
-rw-rw-rw-@   1 onixon  staff       98722 Sep  3  2019 MADTRB11.ZIP
-rw-rw-rw-@   1 onixon  staff       94931 Sep  3  2019 MADTRB12.ZIP
-rw-rw-rw-@   1 onixon  staff      110435 Sep  3  2019 MADTRB13.ZIP
-rw-rw-rw-@   1 onixon  staff       88618 Sep  3  2019 MADTRB14.ZIP
-rw-rw-rw-@   1 onixon  staff      113603 Sep  3  2019 MADTRB15.ZIP
-rw-rw-rw-@   1 onixon  staff       80751 Sep  3  2019 MADTRB16.ZIP
-rw-rw-rw-@   1 onixon  staff      119493 Sep  3  2019 MADTRB17.ZIP
-rw-rw-rw-@   1 onixon  staff      112073 Sep  3  2019 MADTRB18.ZIP
-rw-rw-rw-@   1 onixon  staff      124476 Sep  3  2019 MADTRB19.ZIP
-rw-rw-rw-@   1 onixon  staff       69838 Sep  3  2019 MADTRB2.ZIP
-rw-rw-rw-@   1 onixon  staff      107288 Sep  3  2019 MADTRB20.ZIP
-rw-rw-rw-@   1 onixon  staff      159064 Sep  3  2019 MADTRB21.ZIP
-rw-rw-rw-@   1 onixon  staff      123359 Sep  3  2019 MADTRB28.ZIP
-rw-rw-rw-@   1 onixon  staff       56775 Sep  3  2019 MADTRB29.ZIP
-rw-rw-rw-@   1 onixon  staff       93892 Sep  3  2019 MADTRB3.ZIP
-rw-rw-rw-@   1 onixon  staff       56131 Sep  3  2019 MADTRB30.ZIP
-rw-rw-rw-@   1 onixon  staff       56131 Sep  3  2019 MADTRB30(1).ZIP
-rw-rw-rw-@   1 onixon  staff       83241 Sep  3  2019 MADTRB31.ZIP
-rw-rw-rw-@   1 onixon  staff      122107 Sep  3  2019 MADTRB32.ZIP
-rw-rw-rw-@   1 onixon  staff       89925 Sep  3  2019 MADTRB33.ZIP
-rw-rw-rw-@   1 onixon  staff       97563 Sep  3  2019 MADTRB34.ZIP
-rw-rw-rw-@   1 onixon  staff      107892 Sep  3  2019 MADTRB35.ZIP
-rw-rw-rw-@   1 onixon  staff       99411 Sep  3  2019 MADTRB36.ZIP
-rw-rw-rw-@   1 onixon  staff       43937 Sep  3  2019 MADTRB37.ZIP
-rw-rw-rw-@   1 onixon  staff      107473 Sep  3  2019 MADTRB38.ZIP
-rw-rw-rw-@   1 onixon  staff       73348 Sep  3  2019 MADTRB39.ZIP
-rw-rw-rw-@   1 onixon  staff      134828 Sep  3  2019 MADTRB4.ZIP
-rw-rw-rw-@   1 onixon  staff      101205 Sep  3  2019 MADTRB40.ZIP
-rw-rw-rw-@   1 onixon  staff      124052 Sep  3  2019 MADTRB5.ZIP
-rw-rw-rw-@   1 onixon  staff       98258 Sep  3  2019 MADTRB7.ZIP
-rw-rw-rw-@   1 onixon  staff      105685 Sep  3  2019 MADTRB8.ZIP
-rw-rw-rw-@   1 onixon  staff       91306 Sep  3  2019 MADTRB9.ZIP
-rw-rw-rw-@   1 onixon  staff        1827 Sep  3  2019 MADTURBO.ZIP
-rw-rw-rw-@   1 onixon  staff        2303 Sep  3  2019 USING.ZIP
-rw-rw-rw-@   1 onixon  staff       31185 Sep  3  2019 TPHYD100.ZIP
-rw-rw-rw-@   1 onixon  staff       18942 Sep  3  2019 LZH_PAS.ZIP
-rw-rw-rw-@   1 onixon  staff       11595 Sep  3  2019 LZSFX.ZIP
-rw-rw-rw-@   1 onixon  staff       16756 Sep  3  2019 RLE.PAS
-rw-rw-rw-@   1 onixon  staff        4201 Sep  3  2019 TICTAC.ZIP
-rw-rw-rw-@   1 onixon  staff      185114 Sep  3  2019 PAS_DEMO.ZIP
-rw-rw-rw-@   1 onixon  staff        6743 Sep  3  2019 ASC2PAS.ZIP
-rw-rw-rw-@   1 onixon  staff       25009 Sep  3  2019 NERDBOWL.ZIP
-rw-rw-rw-@   1 onixon  staff       45384 Sep  3  2019 PSGUI130.ZIP
-rw-rw-rw-@   1 onixon  staff        6015 Sep  3  2019 PSLST100.ZIP
-rw-rw-rw-@   1 onixon  staff       25165 Sep  3  2019 PSPPD100.ZIP
-rw-rw-rw-@   1 onixon  staff        5259 Sep  3  2019 PSSTK101.ZIP
-rw-rw-rw-@   1 onixon  staff       11508 Sep  3  2019 PSSTR102.ZIP
-rw-rw-rw-@   1 onixon  staff        5414 Sep  3  2019 QWRIT11.ZIP
-rw-rw-rw-@   1 onixon  staff       45521 Sep  3  2019 RMDOOR30.ZIP
-rw-rw-rw-@   1 onixon  staff       41104 Sep  3  2019 MNG132.ZIP
-rw-rw-rw-@   1 onixon  staff        2364 Sep  3  2019 EKEYS11B.ZIP
-rw-rw-rw-@   1 onixon  staff        4082 Sep  3  2019 EMSI.ZIP
-rw-rw-rw-@   1 onixon  staff       26809 Sep  3  2019 HOB100.ZIP
-rw-rw-rw-@   1 onixon  staff       68429 Sep  3  2019 POWRDOOR.ZIP
-rw-rw-rw-@   1 onixon  staff       44847 Sep  3  2019 WEDITS22.ZIP
-rw-rw-rw-@   1 onixon  staff      270261 Sep  3  2019 NUM_RECI.ZIP
-rw-rw-rw-@   1 onixon  staff       67657 Sep  3  2019 PCL4P42.ZIP
-rw-rw-rw-@   1 onixon  staff      161722 Sep  3  2019 WINDOB10.ZIP
-rw-rw-rw-@   1 onixon  staff      240268 Sep  3  2019 AGTSRC(1).ZIP
-rw-rw-rw-@   1 onixon  staff      107456 Sep  3  2019 TSPA3370.ZIP
-rw-rw-rw-@   1 onixon  staff       10020 Sep  3  2019 AFDEV431.ZIP
-rw-rw-rw-@   1 onixon  staff      123095 Sep  4  2019 TURKIT01.ZIP
-rw-rw-rw-@   1 onixon  staff        5597 Sep  4  2019 HEAP7.PAS
-rw-rw-rw-@   1 onixon  staff        8378 Sep  4  2019 BPOS.ZIP
-rw-rw-rw-@   1 onixon  staff        5392 Sep  4  2019 FINPUT.ZIP
-rw-rw-rw-@   1 onixon  staff      247077 Sep  4  2019 AVTS11.ZIP
-rw-rw-rw-@   1 onixon  staff       83158 Sep  4  2019 TMODEM.ZIP
-rw-rw-rw-@   1 onixon  staff       54181 Sep  4  2019 TI_PAS1.ZIP
-rw-rw-rw-@   1 onixon  staff       54472 Sep  4  2019 TI_PAS2.ZIP
-rw-rw-rw-@   1 onixon  staff       77392 Sep  4  2019 TI_PAS3.ZIP
-rw-rw-rw-@   1 onixon  staff       11955 Sep  4  2019 ODBC.ZIP
-rw-rw-rw-@   1 onixon  staff        4410 Sep  5  2019 PARSCL.PAS
-rw-rw-rw-@   1 onixon  staff      323277 Sep 19  2019 pascal_gui.zip
drwxrwxrwx@  20 onixon  staff         680 Sep 19  2019 pascal_gui
-rw-rw-rw-@   1 onixon  staff     1185629 Sep 20  2019 gvsg2102.zip
-rw-rw-rw-@   1 onixon  staff     1462390 Sep 20  2019 Pascal_2019-3859.zip
-rw-rw-rw-@   1 onixon  staff      585066 Oct 16  2019 P063S907.ZIP
-rw-rw-rw-@   1 onixon  staff      702341 Oct 16  2019 P063B907.ZIP
drwx------@  41 onixon  staff        1394 Oct 16  2019 P063B907
-rw-rw-rw-@   1 onixon  staff       51304 Nov 18  2019 intrfc63.zip
drwx------@  20 onixon  staff         680 Nov 18  2019 intrfc63
-rw-rw-rw-@   1 onixon  staff     1296384 Jan 11  2020 qodem-1.0.0.dmg
-rw-rw-rw-@   1 onixon  staff     2528880 Jan 28  2020 CBASIC_Compiler_CB86_Programmers_Guide_May83.pdf
-rw-rw-rw-@   1 onixon  staff      161477 Jan 28  2020 Digital Research CBASIC-86 Compiler 2.0 for MS-DOS.7z
drwxr-xr-x@   4 onixon  staff         136 Jan 28  2020 Digital Research CBASIC-86 Compiler 2.0 for MS-DOS
-rw-rw-rw-@   1 onixon  staff     5454591 Jan 28  2020 Paintbrush-2.5.0.zip
-rw-rw-rw-@   1 onixon  staff       56679 Jan 28  2020 README.ans
-rw-rw-rw-@   1 onixon  staff     1099953 Jan 29  2020 SheepShaver_2.5_20190504.zip
-rw-rw-rw-@   1 onixon  staff    20320627 Jan 29  2020 WPExport.zip
-rw-rw-rw-@   1 onixon  staff      210002 Jan 29  2020 SwiftLink-232-application-notes-(revised).pdf
-rw-rw-rw-@   1 onixon  staff      803741 Jan 30  2020 AdobeFlashPlayer_32_a_install.dmg
-rw-rw-rw-@   1 onixon  staff     3486448 Jan 30  2020 aspell-0.60.8.tar.gz
-rw-r--r--@   1 onixon  staff   111889586 Jan 31  2020 Brave-Browser-QUK420.pkg
-rw-r--r--@   1 onixon  staff        3985 Jan 31  2020 cxc_legacyxbbs2020_newheader(1).ans
-rw-r--r--@   1 onixon  staff        3845 Jan 31  2020 cxc_legacyxbbs2020_newheader.ans
-rw-r--r--@   1 onixon  staff    17210493 Feb  2  2020 Elsinore.ScreenConnect.ClientSetup-1.pkg
drwxr-xr-x   29 onixon  staff         986 Feb  6  2020 prokit
-rw-r--r--@   1 onixon  staff        2617 Feb 11  2020 userlist.ans
-rw-r--r--@   1 onixon  staff       60257 Feb 11  2020 CTM9211.ZIP
drwx------@  34 onixon  staff        1156 Feb 11  2020 CTM9211
-rw-r--r--@   1 onixon  staff       83323 May 16  2020 ppl4p10.zip
drwx------@  30 onixon  staff        1020 May 16  2020 ppl4p10 2
-rw-r--r--@   1 onixon  staff  1389300837 Feb 12  2021 VID10.m4v
-rw-r--r--@   1 onixon  staff   445778221 Feb 17  2021 VID1.m4v
-rw-r--r--@   1 onixon  staff   467341109 Feb 17  2021 VID2.m4v
-rw-r--r--@   1 onixon  staff   805767422 Feb 17  2021 VID3.m4v
-rw-r--r--@   1 onixon  staff   411885285 Feb 17  2021 VID4.m4v
-rw-r--r--@   1 onixon  staff   654812771 Feb 17  2021 VID5.m4v
-rw-r--r--@   1 onixon  staff   700465742 Feb 17  2021 VID6.m4v
-rw-r--r--@   1 onixon  staff   485996282 Feb 17  2021 VID7.m4v
-rw-r--r--@   1 onixon  staff    33960756 Feb 17  2021 VID8.m4v
-rw-r--r--@   1 onixon  staff   235579568 Feb 17  2021 VID9.m4v
-rw-r--r--@   1 onixon  staff   127059868 Mar  5  2021 launcher.dmg
-rw-r--r--@   1 onixon  staff        8117 Mar 17  2021 md5asm32.zip
drwx------@   8 onixon  staff         272 Mar 17  2021 md5asm32
-rw-r--r--@   1 onixon  staff       91729 Mar 17  2021 16575_ultrapascal.ZIP
-rw-r--r--@   1 onixon  staff       91729 Mar 17  2021 16575_ultrapascal-1.ZIP
drwx------@  20 onixon  staff         680 Mar 17  2021 16575_ultrapascal-1
-rw-rw-rw-@   1 onixon  staff   936713450 Sep 15 12:18 CodeTyphonIns.zip
drwx------@  12 onixon  staff         408 Sep 15 14:52 CodeTyphonIns 2
-rw-r--r--@   1 onixon  staff       22532 Sep 15 14:52 .DS_Store
-rw-r--r--@   1 onixon  staff    62508008 Sep 18 18:43 Telegram.dmg
drwxr-xr-x+  29 onixon  staff         986 Sep 21 18:19 ..
-rw-r--r--@   1 onixon  staff        4616 Sep 23 16:07 iris-data.csv
drwxr-xr-x+ 413 onixon  staff       14042 Sep 23 16:08 .
StoleYourWiFi:Downloads onixon$ vim iris-data.csv 
StoleYourWiFi:Downloads onixon$ ls *.SQL
IRISDATA.SQL
StoleYourWiFi:Downloads onixon$ cim IRISDATA.SQL 
-bash: cim: command not found
StoleYourWiFi:Downloads onixon$ vim IRISDATA.SQL 
StoleYourWiFi:Downloads onixon$ vim IMDIV.SQL
StoleYourWiFi:Downloads onixon$ cp IMDIV.SQL IMDEPT.SQL
StoleYourWiFi:Downloads onixon$ vim IMDEPT.SQL 
StoleYourWiFi:Downloads onixon$ vim IMDIV.SQL
StoleYourWiFi:Downloads onixon$ vim IMDEPT.SQL 
StoleYourWiFi:Downloads onixon$ cat IMDIV.SQL
DROP TABLE IMDIV;

CREATE TABLE IMDIV (
ID AUTOINC NOT NULL PRIMARY KEY,
DIV VARCHAR(2),
CAPTION VARCHAR(50)
);

CREATE UNIQUE INDEX BYDIV ON IMDIV(DIV);

INSERT INTO IMDIV (DIV,CAPTION) VALUES('10','Breakfast'),
('20','Lunch'),
('30','Desserts'),
('40','Beverages'),
('50','Snacks'),
('98','Taxable Merchandise'),
('99','Non-Taxable Merchandise');
StoleYourWiFi:Downloads onixon$ cp IMDIV.SQL IMDIV.MYSQL
StoleYourWiFi:Downloads onixon$ vim IMDIV.MYSQL 
StoleYourWiFi:Downloads onixon$ cat IMDIV.MYSQL 
DROP TABLE IMDIV;

CREATE TABLE IMDIV (
ID BIGINT AUTO_INCREMENT,
DIV VARCHAR(2),
CAPTION VARCHAR(50),
PRIMARY KEY(ID)
);

CREATE UNIQUE INDEX BYDIV ON IMDIV(DIV);

INSERT INTO IMDIV (DIV,CAPTION) VALUES('10','Breakfast'),
('20','Lunch'),
('30','Desserts'),
('40','Beverages'),
('50','Snacks'),
('98','Taxable Merchandise'),
('99','Non-Taxable Merchandise');
StoleYourWiFi:Downloads onixon$ vim IMDIV.MYSQL 
StoleYourWiFi:Downloads onixon$ cp IMDEPT.SQL IMDEPT.MYSQL
StoleYourWiFi:Downloads onixon$ vim IMDEPT.MYSQL
StoleYourWiFi:Downloads onixon$ vim IMDIV.MYSQL 
StoleYourWiFi:Downloads onixon$ vim IMDEPT.MYSQL
StoleYourWiFi:Downloads onixon$ vim IMDEPT.SQL
StoleYourWiFi:Downloads onixon$ cp IMDEPT.SQL IMCLASS.SQL
StoleYourWiFi:Downloads onixon$ vim IMCLASS.SQL
StoleYourWiFi:Downloads onixon$ cd /source/LAZARUS/PSQLClient/
StoleYourWiFi:PSQLClient onixon$ ls -alrt Archive.zip 
-rw-r--r--  1 onixon  wheel  3611180 Sep 25 22:16 Archive.zip
StoleYourWiFi:PSQLClient onixon$ scp Archive.zip root@modernpascal.com:/source/
root@modernpascal.com's password: 
Archive.zip                                                                                        100% 3527KB   3.4MB/s   00:01    
StoleYourWiFi:PSQLClient onixon$ cd
StoleYourWiFi:~ onixon$ cd Downloads/
StoleYourWiFi:Downloads onixon$ vim GSTATES.SQL

/**/

DROP TABLE IF EXISTS IMDIV;
DROP TABLE IF EXISTS IMDEPT;
DROP TABLE IF EXISTS IMCLASS;
DROP TABLE IF EXISTS GSTATES;

CREATE TABLE IMDIV (
ID AUTOINC NOT NULL PRIMARY KEY,
DIV VARCHAR(2) UNIQUE,
CAPTION VARCHAR(50)
);

CREATE TABLE IMDEPT (
ID AUTOINC NOT NULL PRIMARY KEY,
PARENT DWORD,
DEPT VARCHAR(3) UNIQUE,
CAPTION VARCHAR(50)
);

CREATE TABLE IMCLASS (
ID AUTOINC NOT NULL PRIMARY KEY,
PARENT DWORD,
CLASS VARCHAR(5) UNIQUE,
CAPTION VARCHAR(50)
);

CREATE TABLE GSTATES (
ID AUTOINC NOT NULL PRIMARY KEY,
STATE VARCHAR(2) UNIQUE,
LATITUDE DECIMAL(10,8),
LONGITUDE DECIMAL(12,8),
NAME VARCHAR(20)
);

/**/

INSERT INTO IMDIV (DIV,CAPTION) VALUES
('10','Breakfast'),
('20','Lunch'),
('30','Desserts'),
('40','Beverages'),
('50','Snacks'),
('98','Taxable Merchandise'),
('99','Non-Taxable Merchandise');

/**/

INSERT INTO IMDEPT (PARENT,DEPT,CAPTION) VALUES
((SELECT ID FROM IMDIV WHERE DIV='10'),'101','Breakfast Plates'),
((SELECT ID FROM IMDIV WHERE DIV='10'),'102','Breakfast Sandwiches'),
((SELECT ID FROM IMDIV WHERE DIV='20'),'201','Lunch Plates'),
((SELECT ID FROM IMDIV WHERE DIV='20'),'202','Lunch Sandwiches'),
((SELECT ID FROM IMDIV WHERE DIV='30'),'301','Desserts Baked'),
((SELECT ID FROM IMDIV WHERE DIV='30'),'302','Desserts Cold'),
((SELECT ID FROM IMDIV WHERE DIV='40'),'401','Cold Drinks'),
((SELECT ID FROM IMDIV WHERE DIV='40'),'402','Hot Drinks'),
((SELECT ID FROM IMDIV WHERE DIV='50'),'501','Chips'),
((SELECT ID FROM IMDIV WHERE DIV='50'),'502','Mixes'),
((SELECT ID FROM IMDIV WHERE DIV='50'),'503','Sweets'),
((SELECT ID FROM IMDIV WHERE DIV='98'),'988','Taxable Merchandise'),
((SELECT ID FROM IMDIV WHERE DIV='99'),'999','Non-Taxable Merchandise');

/**/

INSERT INTO IMCLASS (PARENT,CLASS,CAPTION) VALUES
((SELECT ID FROM IMDEPT WHERE DEPT='101'),'10101','Breakfast Plates Non-Combos'),
((SELECT ID FROM IMDEPT WHERE DEPT='101'),'10102','Breakfast Plates Combination'),
((SELECT ID FROM IMDEPT WHERE DEPT='102'),'10201','Breakfast Sandwiches'),
((SELECT ID FROM IMDEPT WHERE DEPT='102'),'10202','Breakfast Burrito/Empanada'),
((SELECT ID FROM IMDEPT WHERE DEPT='201'),'20101','Hot Lunch Sandwiches'),
((SELECT ID FROM IMDEPT WHERE DEPT='201'),'20102','Hot Lunch Red Meat'),
((SELECT ID FROM IMDEPT WHERE DEPT='201'),'20103','Hot Lunch Poultry'),
((SELECT ID FROM IMDEPT WHERE DEPT='201'),'20104','Hot Lunch Seafood'),
((SELECT ID FROM IMDEPT WHERE DEPT='202'),'20201','Lunch Sandwiches'),
((SELECT ID FROM IMDEPT WHERE DEPT='202'),'20202','Lunch Subs'),
((SELECT ID FROM IMDEPT WHERE DEPT='301'),'30101','Muffins'),
((SELECT ID FROM IMDEPT WHERE DEPT='301'),'30102','Cookies'),
((SELECT ID FROM IMDEPT WHERE DEPT='301'),'30103','Pies'),
((SELECT ID FROM IMDEPT WHERE DEPT='301'),'30104','Cakes'),
((SELECT ID FROM IMDEPT WHERE DEPT='301'),'30105','Bars'),
((SELECT ID FROM IMDEPT WHERE DEPT='302'),'30201','Puddings'),
((SELECT ID FROM IMDEPT WHERE DEPT='401'),'40101','Coke Products'),
((SELECT ID FROM IMDEPT WHERE DEPT='401'),'40102','Pepsi Products'),
((SELECT ID FROM IMDEPT WHERE DEPT='401'),'40103','Juices'),
((SELECT ID FROM IMDEPT WHERE DEPT='401'),'40104','Teas'),
((SELECT ID FROM IMDEPT WHERE DEPT='402'),'40201','Coffees'),
((SELECT ID FROM IMDEPT WHERE DEPT='501'),'50101','Potato Chips'),
((SELECT ID FROM IMDEPT WHERE DEPT='501'),'50102','Corn Chips'),
((SELECT ID FROM IMDEPT WHERE DEPT='501'),'50103','Crackers'),
((SELECT ID FROM IMDEPT WHERE DEPT='502'),'50201','Trail Mixes'),
((SELECT ID FROM IMDEPT WHERE DEPT='502'),'50202','Chip Mixes'),
((SELECT ID FROM IMDEPT WHERE DEPT='988'),'98888','Taxable Merchandise'),
((SELECT ID FROM IMDEPT WHERE DEPT='999'),'99999','Non-Taxable Merchandise');

/**/

INSERT INTO GSTATES (STATE,LATITUDE,LONGITUDE,NAME) VALUES
('AK',63.588753,-154.493062,'Alaska'),
('AL',32.318231,-86.902298,'Alabama'),
('AR',35.20105,-91.831833,'Arkansas'),
('AZ',34.048928,-111.093731,'Arizona'),
('CA',36.778261,-119.417932,'California'),
('CO',39.550051,-105.782067,'Colorado'),
('CT',41.603221,-73.087749,'Connecticut'),
('DC',38.905985,-77.033418,'District of Columbia'),
('DE',38.910832,-75.52767,'Delaware'),
('FL',27.664827,-81.515754,'Florida'),
('GA',32.157435,-82.907123,'Georgia'),
('HI',19.898682,-155.665857,'Hawaii'),
('IA',41.878003,-93.097702,'Iowa'),
('ID',44.068202,-114.742041,'Idaho'),
('IL',40.633125,-89.398528,'Illinois'),
('IN',40.551217,-85.602364,'Indiana'),
('KS',39.011902,-98.484246,'Kansas'),
('KY',37.839333,-84.270018,'Kentucky'),
('LA',31.244823,-92.145024,'Louisiana'),
('MA',42.407211,-71.382437,'Massachusetts'),
('MD',39.045755,-76.641271,'Maryland'),
('ME',45.253783,-69.445469,'Maine'),
('MI',44.314844,-85.602364,'Michigan'),
('MN',46.729553,-94.6859,'Minnesota'),
('MO',37.964253,-91.831833,'Missouri'),
('MS',32.354668,-89.398528,'Mississippi'),
('MT',46.879682,-110.362566,'Montana'),
('NC',35.759573,-79.0193,'North Carolina'),
('ND',47.551493,-101.002012,'North Dakota'),
('NE',41.492537,-99.901813,'Nebraska'),
('NH',43.193852,-71.572395,'New Hampshire'),
('NJ',40.058324,-74.405661,'New Jersey'),
('NM',34.97273,-105.032363,'New Mexico'),
('NV',38.80261,-116.419389,'Nevada'),
('NY',43.299428,-74.217933,'New York'),
('OH',40.417287,-82.907123,'Ohio'),
('OK',35.007752,-97.092877,'Oklahoma'),
('OR',43.804133,-120.554201,'Oregon'),
('PA',41.203322,-77.194525,'Pennsylvania'),
('PR',18.220833,-66.590149,'Puerto Rico'),
('RI',41.580095,-71.477429,'Rhode Island'),
('SC',33.836081,-81.163725,'South Carolina'),
('SD',43.969515,-99.901813,'South Dakota'),
('TN',35.517491,-86.580447,'Tennessee'),
('TX',31.968599,-99.901813,'Texas'),
('UT',39.32098,-111.093731,'Utah'),
('VA',37.431573,-78.656894,'Virginia'),
('VT',44.558803,-72.577841,'Vermont'),
('WA',47.751074,-120.740139,'Washington'),
('WI',43.78444,-88.787868,'Wisconsin'),
('WV',38.597626,-80.454903,'West Virginia'),
('WY',43.075968,-107.290284,'Wyoming');

/**/
